/* eslint-disable no-constant-condition */
import * as peg from 'peggy';
import * as T from './types';
import { OpCodes } from './opcodes';
export default function (): peg.Parser {
  const module = { exports: null };
  /*
   * Generated by PEG.js 0.10.0.
   *
   * http://pegjs.org/
   */

  ('use strict');

  function peg$subclass(child, parent) {
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor();
  }

  function peg$SyntaxError(message, expected, found, location) {
    this.message = message;
    this.expected = expected;
    this.found = found;
    this.location = location;
    this.name = 'SyntaxError';

    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, peg$SyntaxError);
    }
  }

  peg$subclass(peg$SyntaxError, Error);

  peg$SyntaxError.buildMessage = function (expected, found) {
    const DESCRIBE_EXPECTATION_FNS = {
      literal: function (expectation) {
        return '"' + literalEscape(expectation.text) + '"';
      },

      class: function (expectation) {
        let escapedParts = '';
        let i;

        for (i = 0; i < expectation.parts.length; i++) {
          escapedParts +=
            expectation.parts[i] instanceof Array
              ? classEscape(expectation.parts[i][0]) + '-' + classEscape(expectation.parts[i][1])
              : classEscape(expectation.parts[i]);
        }

        return '[' + (expectation.inverted ? '^' : '') + escapedParts + ']';
      },

      any: function (expectation) {
        return 'any character';
      },

      end: function (expectation) {
        return 'end of input';
      },

      other: function (expectation) {
        return expectation.description;
      },
    };

    function hex(ch) {
      return ch.charCodeAt(0).toString(16).toUpperCase();
    }

    function literalEscape(s) {
      return s
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(/\0/g, '\\0')
        .replace(/\t/g, '\\t')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/[\x00-\x0F]/g, function (ch) {
          return '\\x0' + hex(ch);
        })
        .replace(/[\x10-\x1F\x7F-\x9F]/g, function (ch) {
          return '\\x' + hex(ch);
        });
    }

    function classEscape(s) {
      return s
        .replace(/\\/g, '\\\\')
        .replace(/\]/g, '\\]')
        .replace(/\^/g, '\\^')
        .replace(/-/g, '\\-')
        .replace(/\0/g, '\\0')
        .replace(/\t/g, '\\t')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/[\x00-\x0F]/g, function (ch) {
          return '\\x0' + hex(ch);
        })
        .replace(/[\x10-\x1F\x7F-\x9F]/g, function (ch) {
          return '\\x' + hex(ch);
        });
    }

    function describeExpectation(expectation) {
      return DESCRIBE_EXPECTATION_FNS[expectation.type](expectation);
    }

    function describeExpected(expected) {
      const descriptions = new Array(expected.length);
      let i;
      let j;

      for (i = 0; i < expected.length; i++) {
        descriptions[i] = describeExpectation(expected[i]);
      }

      descriptions.sort();

      if (descriptions.length > 0) {
        for (i = 1, j = 1; i < descriptions.length; i++) {
          if (descriptions[i - 1] !== descriptions[i]) {
            descriptions[j] = descriptions[i];
            j++;
          }
        }
        descriptions.length = j;
      }

      switch (descriptions.length) {
        case 1:
          return descriptions[0];

        case 2:
          return descriptions[0] + ' or ' + descriptions[1];

        default:
          return descriptions.slice(0, -1).join(', ') + ', or ' + descriptions[descriptions.length - 1];
      }
    }

    function describeFound(found) {
      return found ? '"' + literalEscape(found) + '"' : 'end of input';
    }

    return 'Expected ' + describeExpected(expected) + ' but ' + describeFound(found) + ' found.';
  };

  function peg$parse(input, options) {
    options = options !== void 0 ? options : {};

    const peg$FAILED = {};

    const peg$startRuleFunctions = { Program: peg$parseProgram };
    let peg$startRuleFunction = peg$parseProgram;

    const peg$c0 = function (c) {
      return c;
    };
    const peg$c1 = peg$otherExpectation('statement');
    const peg$c2 = peg$otherExpectation('comment');
    const peg$c3 = '//';
    const peg$c4 = peg$literalExpectation('//', false);
    const peg$c5 = /^[^\n]/;
    const peg$c6 = peg$classExpectation(['\n'], true, false);
    const peg$c7 = function () {
      return [];
    };
    const peg$c8 = peg$otherExpectation('system instruction');
    const peg$c9 = 'delay';
    const peg$c10 = peg$literalExpectation('delay', false);
    const peg$c11 = function (delay) {
      return [OpCodes.Delay, ...delay];
    };
    const peg$c12 = 'sleep';
    const peg$c13 = peg$literalExpectation('sleep', false);
    const peg$c14 = function (delay) {
      return [OpCodes.Sleep, ...delay];
    };
    const peg$c15 = 'halt';
    const peg$c16 = peg$literalExpectation('halt', false);
    const peg$c17 = function () {
      return [OpCodes.Halt];
    };
    const peg$c18 = 'restart';
    const peg$c19 = peg$literalExpectation('restart', false);
    const peg$c20 = function () {
      return [OpCodes.Restart];
    };
    const peg$c21 = 'noop';
    const peg$c22 = peg$literalExpectation('noop', false);
    const peg$c23 = function () {
      return [OpCodes.Noop];
    };
    const peg$c24 = 'jump';
    const peg$c25 = peg$literalExpectation('jump', false);
    const peg$c26 = 'to';
    const peg$c27 = peg$literalExpectation('to', false);
    const peg$c28 = function (address) {
      return [OpCodes.JumpTo, ...address];
    };
    const peg$c29 = function (label) {
      return [OpCodes.JumpTo, T.Placeholder.create(label), 0, 0, 0];
    };
    const peg$c30 = 'if';
    const peg$c31 = peg$literalExpectation('if', false);
    const peg$c32 = 'then';
    const peg$c33 = peg$literalExpectation('then', false);
    const peg$c34 = function (condition, label) {
      return [OpCodes.JumpIf, ...condition, T.Placeholder.create(label), 0, 0, 0];
    };
    const peg$c35 = 'yield';
    const peg$c36 = peg$literalExpectation('yield', false);
    const peg$c37 = function (delay) {
      return [OpCodes.Yield, ...delay];
    };
    const peg$c38 = 'sysinfo';
    const peg$c39 = peg$literalExpectation('sysinfo', false);
    const peg$c40 = function () {
      return [OpCodes.SystemInfo];
    };
    const peg$c41 = 'debug';
    const peg$c42 = peg$literalExpectation('debug', false);
    const peg$c43 = function (byte) {
      return [OpCodes.Debug, byte];
    };
    const peg$c44 = 'dump';
    const peg$c45 = peg$literalExpectation('dump', false);
    const peg$c46 = function () {
      return [OpCodes.Dump];
    };
    const peg$c47 = 'print';
    const peg$c48 = peg$literalExpectation('print', false);
    const peg$c49 = function (value) {
      return [OpCodes.Print, ...value];
    };
    const peg$c50 = /^[a-zA-Z]/;
    const peg$c51 = peg$classExpectation(
      [
        ['a', 'z'],
        ['A', 'Z'],
      ],
      false,
      false,
    );
    const peg$c52 = /^[a-zA-Z0-9_]/;
    const peg$c53 = peg$classExpectation([['a', 'z'], ['A', 'Z'], ['0', '9'], '_'], false, false);
    const peg$c54 = function () {
      return text();
    };
    const peg$c55 = 'fn';
    const peg$c56 = peg$literalExpectation('fn', false);
    const peg$c57 = function (label) {
      return T.Reference.create(label);
    };
    const peg$c58 = 'var';
    const peg$c59 = peg$literalExpectation('var', false);
    const peg$c60 = function (t) {
      return T.DeclareIdentifier.create(t);
    };
    const peg$c61 = 'memget';
    const peg$c62 = peg$literalExpectation('memget', false);
    const peg$c63 = function () {
      return [0x05];
    };
    const peg$c64 = 'memset';
    const peg$c65 = peg$literalExpectation('memset', false);
    const peg$c66 = function () {
      return [0x06];
    };
    const peg$c67 = 'copy';
    const peg$c68 = peg$literalExpectation('copy', false);
    const peg$c69 = function () {
      return [0x1b];
    };
    const peg$c70 = 'not';
    const peg$c71 = peg$literalExpectation('not', false);
    const peg$c72 = function (target, value) {
      return [0x13, target, value];
    };
    const peg$c73 = 'gte';
    const peg$c74 = peg$literalExpectation('gte', false);
    const peg$c75 = function () {
      return [0x0a];
    };
    const peg$c76 = 'gt';
    const peg$c77 = peg$literalExpectation('gt', false);
    const peg$c78 = function () {
      return [0x09];
    };
    const peg$c79 = 'lte';
    const peg$c80 = peg$literalExpectation('lte', false);
    const peg$c81 = function () {
      return [0x0c];
    };
    const peg$c82 = 'lt';
    const peg$c83 = peg$literalExpectation('lt', false);
    const peg$c84 = function () {
      return [0x0b];
    };
    const peg$c85 = 'equal';
    const peg$c86 = peg$literalExpectation('equal', false);
    const peg$c87 = function () {
      return [0x0d];
    };
    const peg$c88 = 'notequal';
    const peg$c89 = peg$literalExpectation('notequal', false);
    const peg$c90 = function () {
      return [0x0e];
    };
    const peg$c91 = 'xor';
    const peg$c92 = peg$literalExpectation('xor', false);
    const peg$c93 = function () {
      return [0x10];
    };
    const peg$c94 = 'and';
    const peg$c95 = peg$literalExpectation('and', false);
    const peg$c96 = function () {
      return [0x11];
    };
    const peg$c97 = 'or';
    const peg$c98 = peg$literalExpectation('or', false);
    const peg$c99 = function () {
      return [0x12];
    };
    const peg$c100 = 'inc';
    const peg$c101 = peg$literalExpectation('inc', false);
    const peg$c102 = function () {
      return [0x14];
    };
    const peg$c103 = 'dec';
    const peg$c104 = peg$literalExpectation('dec', false);
    const peg$c105 = function () {
      return [0x15];
    };
    const peg$c106 = 'add';
    const peg$c107 = peg$literalExpectation('add', false);
    const peg$c108 = function () {
      return [0x16];
    };
    const peg$c109 = 'sub';
    const peg$c110 = peg$literalExpectation('sub', false);
    const peg$c111 = function () {
      return [0x17];
    };
    const peg$c112 = 'mul';
    const peg$c113 = peg$literalExpectation('mul', false);
    const peg$c114 = function () {
      return [0x18];
    };
    const peg$c115 = 'div';
    const peg$c116 = peg$literalExpectation('div', false);
    const peg$c117 = function () {
      return [0x19];
    };
    const peg$c118 = 'mod';
    const peg$c119 = peg$literalExpectation('mod', false);
    const peg$c120 = function () {
      return [0x1a];
    };
    const peg$c121 = 'io write';
    const peg$c122 = peg$literalExpectation('io write', false);
    const peg$c123 = function (pin, value) {
      return [OpCodes.IoWrite, pin, ...value];
    };
    const peg$c124 = 'io read';
    const peg$c125 = peg$literalExpectation('io read', false);
    const peg$c126 = function (pin, value) {
      return [OpCodes.IoRead, pin, ...value];
    };
    const peg$c127 = 'io mode';
    const peg$c128 = peg$literalExpectation('io mode', false);
    const peg$c129 = function (pin, mode) {
      return [OpCodes.IoMode, pin, mode];
    };
    const peg$c130 = 'io type';
    const peg$c131 = peg$literalExpectation('io type', false);
    const peg$c132 = function (pin, type) {
      return [OpCodes.IoType, pin, type];
    };
    const peg$c133 = 'io allout';
    const peg$c134 = peg$literalExpectation('io allout', false);
    const peg$c135 = function () {
      return [OpCodes.IoAllOut];
    };
    const peg$c136 = 'net connect';
    const peg$c137 = peg$literalExpectation('net connect', false);
    const peg$c138 = function (net, pwd) {
      return [0x3a, ...net, ...pwd];
    };
    const peg$c139 = 'net disconnect';
    const peg$c140 = peg$literalExpectation('net disconnect', false);
    const peg$c141 = function () {
      return [0x3b];
    };
    const peg$c142 = 'net status';
    const peg$c143 = peg$literalExpectation('net status', false);
    const peg$c144 = function () {
      return [0x3c];
    };
    const peg$c145 = 'net list';
    const peg$c146 = peg$literalExpectation('net list', false);
    const peg$c147 = function () {
      return [0x3e];
    };
    const peg$c148 = 'i2setup';
    const peg$c149 = peg$literalExpectation('i2setup', false);
    const peg$c150 = function () {
      return [0x40];
    };
    const peg$c151 = 'i2start';
    const peg$c152 = peg$literalExpectation('i2start', false);
    const peg$c153 = function () {
      return [0x41];
    };
    const peg$c154 = 'i2stop';
    const peg$c155 = peg$literalExpectation('i2stop', false);
    const peg$c156 = function () {
      return [0x42];
    };
    const peg$c157 = 'i2write';
    const peg$c158 = peg$literalExpectation('i2write', false);
    const peg$c159 = function () {
      return [0x43];
    };
    const peg$c160 = 'i2read';
    const peg$c161 = peg$literalExpectation('i2read', false);
    const peg$c162 = function () {
      return [0x44];
    };
    const peg$c163 = 'i2setack';
    const peg$c164 = peg$literalExpectation('i2setack', false);
    const peg$c165 = function () {
      return [0x45];
    };
    const peg$c166 = 'i2getack';
    const peg$c167 = peg$literalExpectation('i2getack', false);
    const peg$c168 = function () {
      return [0x46];
    };
    const peg$c169 = 'i2find';
    const peg$c170 = peg$literalExpectation('i2find', false);
    const peg$c171 = function () {
      return [0x48];
    };
    const peg$c172 = 'i2writeack';
    const peg$c173 = peg$literalExpectation('i2writeack', false);
    const peg$c174 = function () {
      return [0x49];
    };
    const peg$c175 = 'i2writeack_b';
    const peg$c176 = peg$literalExpectation('i2writeack_b', false);
    const peg$c177 = function () {
      return [0x4a];
    };
    const peg$c178 = peg$otherExpectation('hexadecimal');
    const peg$c179 = /^[0-9A-Fa-f]/;
    const peg$c180 = peg$classExpectation(
      [
        ['0', '9'],
        ['A', 'F'],
        ['a', 'f'],
      ],
      false,
      false,
    );
    const peg$c181 = peg$otherExpectation('byte hex');
    const peg$c182 = peg$otherExpectation('Byte');
    const peg$c183 = '0x';
    const peg$c184 = peg$literalExpectation('0x', false);
    const peg$c185 = function () {
      return parseInt(text(), 16);
    };
    const peg$c186 = /^[ \t]/;
    const peg$c187 = peg$classExpectation([' ', '\t'], false, false);
    const peg$c188 = peg$otherExpectation('space');
    const peg$c189 = peg$otherExpectation('new line');
    const peg$c190 = /^[\n]/;
    const peg$c191 = peg$classExpectation(['\n'], false, false);
    const peg$c192 = peg$otherExpectation('separator');
    const peg$c193 = ',';
    const peg$c194 = peg$literalExpectation(',', false);
    const peg$c195 = peg$otherExpectation('0..9');
    const peg$c196 = /^[0-9]/;
    const peg$c197 = peg$classExpectation([['0', '9']], false, false);
    const peg$c198 = peg$otherExpectation('1..9');
    const peg$c199 = /^[1-9]/;
    const peg$c200 = peg$classExpectation([['1', '9']], false, false);
    const peg$c201 = peg$otherExpectation('a-z');
    const peg$c202 = /^[a-z]/i;
    const peg$c203 = peg$classExpectation([['a', 'z']], false, true);
    const peg$c204 = peg$otherExpectation('a-z or 0-9');
    const peg$c205 = peg$otherExpectation('pin mode');
    const peg$c206 = /^[0-3]/;
    const peg$c207 = peg$classExpectation([['0', '3']], false, false);
    const peg$c208 = function (mode) {
      return Number(mode);
    };
    const peg$c209 = 'true';
    const peg$c210 = peg$literalExpectation('true', false);
    const peg$c211 = '1';
    const peg$c212 = peg$literalExpectation('1', false);
    const peg$c213 = function () {
      return 1;
    };
    const peg$c214 = 'false';
    const peg$c215 = peg$literalExpectation('false', false);
    const peg$c216 = '0';
    const peg$c217 = peg$literalExpectation('0', false);
    const peg$c218 = function () {
      return 0;
    };
    const peg$c219 = peg$otherExpectation('integer');
    const peg$c220 = function () {
      return parseInt(text());
    };
    const peg$c221 = '-';
    const peg$c222 = peg$literalExpectation('-', false);
    const peg$c223 = function (int) {
      return -1 * int;
    };
    const peg$c224 = peg$otherExpectation('string');
    const peg$c225 = "'";
    const peg$c226 = peg$literalExpectation("'", false);
    const peg$c227 = peg$anyExpectation();
    const peg$c228 = function (string) {
      return string.map((s) => s[1]);
    };
    const peg$c229 = peg$otherExpectation('address');
    const peg$c230 = function (a, b, c, d) {
      return [d, c, b, a];
    };
    const peg$c231 = peg$otherExpectation('pin');
    const peg$c232 = 'pin ';
    const peg$c233 = peg$literalExpectation('pin ', false);
    const peg$c234 = '10';
    const peg$c235 = peg$literalExpectation('10', false);
    const peg$c236 = '11';
    const peg$c237 = peg$literalExpectation('11', false);
    const peg$c238 = '12';
    const peg$c239 = peg$literalExpectation('12', false);
    const peg$c240 = '13';
    const peg$c241 = peg$literalExpectation('13', false);
    const peg$c242 = '14';
    const peg$c243 = peg$literalExpectation('14', false);
    const peg$c244 = '15';
    const peg$c245 = peg$literalExpectation('15', false);
    const peg$c246 = function (pin) {
      return Number(pin);
    };
    const peg$c247 = peg$otherExpectation('identifier');
    const peg$c248 = '$';
    const peg$c249 = peg$literalExpectation('$', false);
    const peg$c250 = function (head, tail) {
      return text();
    };
    const peg$c251 = '_';
    const peg$c252 = peg$literalExpectation('_', false);
    const peg$c253 = function (name) {
      return T.IdentifierValue.create(name);
    };
    const peg$c254 = function (pin) {
      return T.PinValue.create(pin);
    };
    const peg$c255 = function (bool) {
      return T.ByteValue.create(bool);
    };
    const peg$c256 = function (byte) {
      return T.ByteValue.create(byte);
    };
    const peg$c257 = function (address) {
      return T.AddressValue.create(address);
    };
    const peg$c258 = function (number) {
      return T.IntegerValue.create(number);
    };
    const peg$c259 = function (number) {
      return T.SignedIntegerValue.create(number);
    };
    const peg$c260 = function (string) {
      return T.StringValue.create(string);
    };
    const peg$c261 = peg$otherExpectation('value');

    let peg$currPos = 0;
    let peg$savedPos = 0;
    const peg$posDetailsCache = [{ line: 1, column: 1 }];
    let peg$maxFailPos = 0;
    let peg$maxFailExpected = [];
    let peg$silentFails = 0;

    let peg$result;

    if ('startRule' in options) {
      if (!(options.startRule in peg$startRuleFunctions)) {
        throw new Error('Can\'t start parsing from rule "' + options.startRule + '".');
      }

      peg$startRuleFunction = peg$startRuleFunctions[options.startRule];
    }

    function text() {
      return input.substring(peg$savedPos, peg$currPos);
    }

    function location() {
      return peg$computeLocation(peg$savedPos, peg$currPos);
    }

    function expected(description, location) {
      location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos);

      throw peg$buildStructuredError(
        [peg$otherExpectation(description)],
        input.substring(peg$savedPos, peg$currPos),
        location,
      );
    }

    function error(message, location) {
      location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos);

      throw peg$buildSimpleError(message, location);
    }

    function peg$literalExpectation(text, ignoreCase) {
      return { type: 'literal', text: text, ignoreCase: ignoreCase };
    }

    function peg$classExpectation(parts, inverted, ignoreCase) {
      return { type: 'class', parts: parts, inverted: inverted, ignoreCase: ignoreCase };
    }

    function peg$anyExpectation() {
      return { type: 'any' };
    }

    function peg$endExpectation() {
      return { type: 'end' };
    }

    function peg$otherExpectation(description) {
      return { type: 'other', description: description };
    }

    function peg$computePosDetails(pos) {
      let details = peg$posDetailsCache[pos];
      let p;

      if (details) {
        return details;
      } else {
        p = pos - 1;
        while (!peg$posDetailsCache[p]) {
          p--;
        }

        details = peg$posDetailsCache[p];
        details = {
          line: details.line,
          column: details.column,
        };

        while (p < pos) {
          if (input.charCodeAt(p) === 10) {
            details.line++;
            details.column = 1;
          } else {
            details.column++;
          }

          p++;
        }

        peg$posDetailsCache[pos] = details;
        return details;
      }
    }

    function peg$computeLocation(startPos, endPos) {
      const startPosDetails = peg$computePosDetails(startPos);
      const endPosDetails = peg$computePosDetails(endPos);

      return {
        start: {
          offset: startPos,
          line: startPosDetails.line,
          column: startPosDetails.column,
        },
        end: {
          offset: endPos,
          line: endPosDetails.line,
          column: endPosDetails.column,
        },
      };
    }

    function peg$fail(expected) {
      if (peg$currPos < peg$maxFailPos) {
        return;
      }

      if (peg$currPos > peg$maxFailPos) {
        peg$maxFailPos = peg$currPos;
        peg$maxFailExpected = [];
      }

      peg$maxFailExpected.push(expected);
    }

    function peg$buildSimpleError(message, location) {
      return new peg$SyntaxError(message, null, null, location);
    }

    function peg$buildStructuredError(expected, found, location) {
      return new peg$SyntaxError(peg$SyntaxError.buildMessage(expected, found), expected, found, location);
    }

    function peg$parseProgram() {
      let s0;
      let s1;
      let s2;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseLine();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseLine();
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c0(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseLine() {
      let s0;
      let s1;
      let s2;
      let s3;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parseSpaces();
      if (s1 !== peg$FAILED) {
        s2 = peg$parseStatement();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseNewLine();
          if (s3 === peg$FAILED) {
            s3 = null;
          }
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c0(s2);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c1);
        }
      }

      return s0;
    }

    function peg$parseComment() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c3) {
        s2 = peg$c3;
        peg$currPos += 2;
      } else {
        s2 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c4);
        }
      }
      if (s2 !== peg$FAILED) {
        s3 = [];
        if (peg$c5.test(input.charAt(peg$currPos))) {
          s4 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s4 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c6);
          }
        }
        if (s4 !== peg$FAILED) {
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            if (peg$c5.test(input.charAt(peg$currPos))) {
              s4 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s4 = peg$FAILED;
              if (peg$silentFails === 0) {
                peg$fail(peg$c6);
              }
            }
          }
        } else {
          s3 = peg$FAILED;
        }
        if (s3 !== peg$FAILED) {
          s2 = [s2, s3];
          s1 = s2;
        } else {
          peg$currPos = s1;
          s1 = peg$FAILED;
        }
      } else {
        peg$currPos = s1;
        s1 = peg$FAILED;
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c7();
      }
      s0 = s1;
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c2);
        }
      }

      return s0;
    }

    function peg$parseStatement() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = peg$parseDefineLabel();
      if (s0 === peg$FAILED) {
        s0 = peg$parseSystemInstruction();
        if (s0 === peg$FAILED) {
          s0 = peg$parseMemoryInstruction();
          if (s0 === peg$FAILED) {
            s0 = peg$parseOperator();
            if (s0 === peg$FAILED) {
              s0 = peg$parseIoInstruction();
              if (s0 === peg$FAILED) {
                s0 = peg$parseWifiInstruction();
                if (s0 === peg$FAILED) {
                  s0 = peg$parseI2cInstruction();
                  if (s0 === peg$FAILED) {
                    s0 = peg$parseComment();
                  }
                }
              }
            }
          }
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c1);
        }
      }

      return s0;
    }

    function peg$parseSystemInstruction() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = peg$parsehalt();
      if (s0 === peg$FAILED) {
        s0 = peg$parserestart();
        if (s0 === peg$FAILED) {
          s0 = peg$parsesysinfo();
          if (s0 === peg$FAILED) {
            s0 = peg$parsedebug();
            if (s0 === peg$FAILED) {
              s0 = peg$parsedump();
              if (s0 === peg$FAILED) {
                s0 = peg$parsenoop();
                if (s0 === peg$FAILED) {
                  s0 = peg$parseyield();
                  if (s0 === peg$FAILED) {
                    s0 = peg$parseprint();
                    if (s0 === peg$FAILED) {
                      s0 = peg$parsejump_to();
                      if (s0 === peg$FAILED) {
                        s0 = peg$parsejump_if();
                        if (s0 === peg$FAILED) {
                          s0 = peg$parsedelay();
                          if (s0 === peg$FAILED) {
                            s0 = peg$parseDeclareVar();
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c8);
        }
      }

      return s0;
    }

    function peg$parsedelay() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 5) === peg$c9) {
        s1 = peg$c9;
        peg$currPos += 5;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c10);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseIntegerValue();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c11(s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        if (input.substr(peg$currPos, 5) === peg$c12) {
          s1 = peg$c12;
          peg$currPos += 5;
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c13);
          }
        }
        if (s1 !== peg$FAILED) {
          s2 = peg$parseSpaces();
          if (s2 !== peg$FAILED) {
            s3 = peg$parseIntegerValue();
            if (s3 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c14(s3);
              s0 = s1;
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      }

      return s0;
    }

    function peg$parsehalt() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c15) {
        s1 = peg$c15;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c16);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c17();
      }
      s0 = s1;

      return s0;
    }

    function peg$parserestart() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c18) {
        s1 = peg$c18;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c19);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c20();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsenoop() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c21) {
        s1 = peg$c21;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c22);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c23();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsejump_to() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c24) {
        s1 = peg$c24;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c25);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          if (input.substr(peg$currPos, 2) === peg$c26) {
            s3 = peg$c26;
            peg$currPos += 2;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c27);
            }
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSpaces();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseAddressValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c28(s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        if (input.substr(peg$currPos, 4) === peg$c24) {
          s1 = peg$c24;
          peg$currPos += 4;
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c25);
          }
        }
        if (s1 !== peg$FAILED) {
          s2 = peg$parseSpaces();
          if (s2 !== peg$FAILED) {
            if (input.substr(peg$currPos, 2) === peg$c26) {
              s3 = peg$c26;
              peg$currPos += 2;
            } else {
              s3 = peg$FAILED;
              if (peg$silentFails === 0) {
                peg$fail(peg$c27);
              }
            }
            if (s3 !== peg$FAILED) {
              s4 = peg$parseSpaces();
              if (s4 !== peg$FAILED) {
                s5 = peg$parseLabel();
                if (s5 !== peg$FAILED) {
                  peg$savedPos = s0;
                  s1 = peg$c29(s5);
                  s0 = s1;
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      }

      return s0;
    }

    function peg$parsejump_if() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;
      let s6;
      let s7;
      let s8;
      let s9;
      let s10;
      let s11;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c30) {
        s1 = peg$c30;
        peg$currPos += 2;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c31);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseValue();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSpaces();
            if (s4 !== peg$FAILED) {
              if (input.substr(peg$currPos, 4) === peg$c32) {
                s5 = peg$c32;
                peg$currPos += 4;
              } else {
                s5 = peg$FAILED;
                if (peg$silentFails === 0) {
                  peg$fail(peg$c33);
                }
              }
              if (s5 !== peg$FAILED) {
                s6 = peg$parseSpaces();
                if (s6 !== peg$FAILED) {
                  if (input.substr(peg$currPos, 4) === peg$c24) {
                    s7 = peg$c24;
                    peg$currPos += 4;
                  } else {
                    s7 = peg$FAILED;
                    if (peg$silentFails === 0) {
                      peg$fail(peg$c25);
                    }
                  }
                  if (s7 !== peg$FAILED) {
                    s8 = peg$parseSpaces();
                    if (s8 !== peg$FAILED) {
                      if (input.substr(peg$currPos, 2) === peg$c26) {
                        s9 = peg$c26;
                        peg$currPos += 2;
                      } else {
                        s9 = peg$FAILED;
                        if (peg$silentFails === 0) {
                          peg$fail(peg$c27);
                        }
                      }
                      if (s9 !== peg$FAILED) {
                        s10 = peg$parseSpaces();
                        if (s10 !== peg$FAILED) {
                          s11 = peg$parseLabel();
                          if (s11 !== peg$FAILED) {
                            peg$savedPos = s0;
                            s1 = peg$c34(s3, s11);
                            s0 = s1;
                          } else {
                            peg$currPos = s0;
                            s0 = peg$FAILED;
                          }
                        } else {
                          peg$currPos = s0;
                          s0 = peg$FAILED;
                        }
                      } else {
                        peg$currPos = s0;
                        s0 = peg$FAILED;
                      }
                    } else {
                      peg$currPos = s0;
                      s0 = peg$FAILED;
                    }
                  } else {
                    peg$currPos = s0;
                    s0 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseyield() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 5) === peg$c35) {
        s1 = peg$c35;
        peg$currPos += 5;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c36);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseIntegerValue();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c37(s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsesysinfo() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c38) {
        s1 = peg$c38;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c39);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c40();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsedebug() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 5) === peg$c41) {
        s1 = peg$c41;
        peg$currPos += 5;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c42);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseBoolean();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c43(s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsedump() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c44) {
        s1 = peg$c44;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c45);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c46();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseprint() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 5) === peg$c47) {
        s1 = peg$c47;
        peg$currPos += 5;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c48);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseValue();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c49(s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseLabel() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      s1 = [];
      if (peg$c50.test(input.charAt(peg$currPos))) {
        s2 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s2 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c51);
        }
      }
      if (s2 !== peg$FAILED) {
        while (s2 !== peg$FAILED) {
          s1.push(s2);
          if (peg$c50.test(input.charAt(peg$currPos))) {
            s2 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s2 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c51);
            }
          }
        }
      } else {
        s1 = peg$FAILED;
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c52.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c53);
          }
        }
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c52.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c53);
            }
          }
        }
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c54();
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseDefineLabel() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c55) {
        s1 = peg$c55;
        peg$currPos += 2;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c56);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseLabel();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c57(s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseDeclareVar() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c58) {
        s1 = peg$c58;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c59);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseIdentifier();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c60(s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseMemoryInstruction() {
      let s0;

      s0 = peg$parsememget();
      if (s0 === peg$FAILED) {
        s0 = peg$parsememset();
        if (s0 === peg$FAILED) {
          s0 = peg$parsecopy();
        }
      }

      return s0;
    }

    function peg$parsememget() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 6) === peg$c61) {
        s1 = peg$c61;
        peg$currPos += 6;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c62);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseIdentifierValue();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c63();
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsememset() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 6) === peg$c64) {
        s1 = peg$c64;
        peg$currPos += 6;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c65);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseMemoryWriteValue();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c66();
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsecopy() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c67) {
        s1 = peg$c67;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c68);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseIdentifierValue();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseValue();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c69();
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseMemoryWriteValue() {
      let s0;

      s0 = peg$parseAddressValue();
      if (s0 === peg$FAILED) {
        s0 = peg$parsePinValue();
      }

      return s0;
    }

    function peg$parseOperator() {
      let s0;

      s0 = peg$parsexor();
      if (s0 === peg$FAILED) {
        s0 = peg$parseand();
        if (s0 === peg$FAILED) {
          s0 = peg$parseor();
          if (s0 === peg$FAILED) {
            s0 = peg$parsenot();
            if (s0 === peg$FAILED) {
              s0 = peg$parseinc();
              if (s0 === peg$FAILED) {
                s0 = peg$parsedec();
                if (s0 === peg$FAILED) {
                  s0 = peg$parseadd();
                  if (s0 === peg$FAILED) {
                    s0 = peg$parsesub();
                    if (s0 === peg$FAILED) {
                      s0 = peg$parsemul();
                      if (s0 === peg$FAILED) {
                        s0 = peg$parsediv();
                        if (s0 === peg$FAILED) {
                          s0 = peg$parsemod();
                          if (s0 === peg$FAILED) {
                            s0 = peg$parsegt();
                            if (s0 === peg$FAILED) {
                              s0 = peg$parsegte();
                              if (s0 === peg$FAILED) {
                                s0 = peg$parselt();
                                if (s0 === peg$FAILED) {
                                  s0 = peg$parselte();
                                  if (s0 === peg$FAILED) {
                                    s0 = peg$parseequal();
                                    if (s0 === peg$FAILED) {
                                      s0 = peg$parsenotequal();
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }

      return s0;
    }

    function peg$parsenot() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c70) {
        s1 = peg$c70;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c71);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseValue();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c72(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsegte() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c73) {
        s1 = peg$c73;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c74);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c75();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsegt() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c76) {
        s1 = peg$c76;
        peg$currPos += 2;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c77);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c78();
      }
      s0 = s1;

      return s0;
    }

    function peg$parselte() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c79) {
        s1 = peg$c79;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c80);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c81();
      }
      s0 = s1;

      return s0;
    }

    function peg$parselt() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c82) {
        s1 = peg$c82;
        peg$currPos += 2;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c83);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c84();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseequal() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 5) === peg$c85) {
        s1 = peg$c85;
        peg$currPos += 5;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c86);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c87();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsenotequal() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 8) === peg$c88) {
        s1 = peg$c88;
        peg$currPos += 8;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c89);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c90();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsexor() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c91) {
        s1 = peg$c91;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c92);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c93();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseand() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c94) {
        s1 = peg$c94;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c95);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c96();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseor() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c97) {
        s1 = peg$c97;
        peg$currPos += 2;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c98);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c99();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseinc() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c100) {
        s1 = peg$c100;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c101);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c102();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsedec() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c103) {
        s1 = peg$c103;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c104);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c105();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseadd() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c106) {
        s1 = peg$c106;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c107);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c108();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsesub() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c109) {
        s1 = peg$c109;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c110);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c111();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsemul() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c112) {
        s1 = peg$c112;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c113);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c114();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsediv() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c115) {
        s1 = peg$c115;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c116);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c117();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsemod() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c118) {
        s1 = peg$c118;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c119);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c120();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseIoInstruction() {
      let s0;

      s0 = peg$parseiowrite();
      if (s0 === peg$FAILED) {
        s0 = peg$parseioread();
        if (s0 === peg$FAILED) {
          s0 = peg$parseiomode();
          if (s0 === peg$FAILED) {
            s0 = peg$parseiotype();
            if (s0 === peg$FAILED) {
              s0 = peg$parseioallout();
            }
          }
        }
      }

      return s0;
    }

    function peg$parseiowrite() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 8) === peg$c121) {
        s1 = peg$c121;
        peg$currPos += 8;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c122);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parsePin();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseIoValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c123(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseioread() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c124) {
        s1 = peg$c124;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c125);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parsePin();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseIoValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c126(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseiomode() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c127) {
        s1 = peg$c127;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c128);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parsePin();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parsePinMode();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c129(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseiotype() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c130) {
        s1 = peg$c130;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c131);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parsePin();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseDigit();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c132(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseioallout() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 9) === peg$c133) {
        s1 = peg$c133;
        peg$currPos += 9;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c134);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c135();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseIoValue() {
      let s0;

      s0 = peg$parseByteValue();
      if (s0 === peg$FAILED) {
        s0 = peg$parseIdentifierValue();
        if (s0 === peg$FAILED) {
          s0 = peg$parseBooleanValue();
        }
      }

      return s0;
    }

    function peg$parseWifiInstruction() {
      let s0;

      s0 = peg$parsewificonnect();
      if (s0 === peg$FAILED) {
        s0 = peg$parsewifidisconnect();
        if (s0 === peg$FAILED) {
          s0 = peg$parsewifistatus();
          if (s0 === peg$FAILED) {
            s0 = peg$parsewifilist();
          }
        }
      }

      return s0;
    }

    function peg$parsewificonnect() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 11) === peg$c136) {
        s1 = peg$c136;
        peg$currPos += 11;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c137);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseStringValue();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseSeparator();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseStringValue();
            if (s4 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c138(s2, s4);
              s0 = s1;
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsewifidisconnect() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 14) === peg$c139) {
        s1 = peg$c139;
        peg$currPos += 14;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c140);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c141();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsewifistatus() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 10) === peg$c142) {
        s1 = peg$c142;
        peg$currPos += 10;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c143);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c144();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsewifilist() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 8) === peg$c145) {
        s1 = peg$c145;
        peg$currPos += 8;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c146);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c147();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseI2cInstruction() {
      let s0;

      s0 = peg$parsei2setup();
      if (s0 === peg$FAILED) {
        s0 = peg$parsei2start();
        if (s0 === peg$FAILED) {
          s0 = peg$parsei2stop();
          if (s0 === peg$FAILED) {
            s0 = peg$parsei2write();
            if (s0 === peg$FAILED) {
              s0 = peg$parsei2read();
              if (s0 === peg$FAILED) {
                s0 = peg$parsei2setack();
                if (s0 === peg$FAILED) {
                  s0 = peg$parsei2getack();
                  if (s0 === peg$FAILED) {
                    s0 = peg$parsei2find();
                    if (s0 === peg$FAILED) {
                      s0 = peg$parsei2writeack();
                      if (s0 === peg$FAILED) {
                        s0 = peg$parsei2writeack_b();
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }

      return s0;
    }

    function peg$parsei2setup() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c148) {
        s1 = peg$c148;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c149);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c150();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsei2start() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c151) {
        s1 = peg$c151;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c152);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c153();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsei2stop() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 6) === peg$c154) {
        s1 = peg$c154;
        peg$currPos += 6;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c155);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c156();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsei2write() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c157) {
        s1 = peg$c157;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c158);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c159();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsei2read() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 6) === peg$c160) {
        s1 = peg$c160;
        peg$currPos += 6;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c161);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c162();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsei2setack() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 8) === peg$c163) {
        s1 = peg$c163;
        peg$currPos += 8;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c164);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c165();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsei2getack() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 8) === peg$c166) {
        s1 = peg$c166;
        peg$currPos += 8;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c167);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c168();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsei2find() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 6) === peg$c169) {
        s1 = peg$c169;
        peg$currPos += 6;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c170);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c171();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsei2writeack() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 10) === peg$c172) {
        s1 = peg$c172;
        peg$currPos += 10;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c173);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c174();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsei2writeack_b() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 12) === peg$c175) {
        s1 = peg$c175;
        peg$currPos += 12;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c176);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c177();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseHexDigit() {
      let s0;
      let s1;

      peg$silentFails++;
      if (peg$c179.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c180);
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c178);
        }
      }

      return s0;
    }

    function peg$parseHexByte() {
      let s0;
      let s1;
      let s2;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parseHexDigit();
      if (s1 !== peg$FAILED) {
        s2 = peg$parseHexDigit();
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c54();
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c181);
        }
      }

      return s0;
    }

    function peg$parseByte() {
      let s0;
      let s1;
      let s2;
      let s3;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c183) {
        s1 = peg$c183;
        peg$currPos += 2;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c184);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseHexDigit();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseHexDigit();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c185();
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c182);
        }
      }

      return s0;
    }

    function peg$parseSpace() {
      let s0;

      if (peg$c186.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c187);
        }
      }

      return s0;
    }

    function peg$parseSpaces() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = [];
      s1 = peg$parseSpace();
      while (s1 !== peg$FAILED) {
        s0.push(s1);
        s1 = peg$parseSpace();
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c188);
        }
      }

      return s0;
    }

    function peg$parseNewLine() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = [];
      if (peg$c190.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c191);
        }
      }
      if (s1 !== peg$FAILED) {
        while (s1 !== peg$FAILED) {
          s0.push(s1);
          if (peg$c190.test(input.charAt(peg$currPos))) {
            s1 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s1 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c191);
            }
          }
        }
      } else {
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c189);
        }
      }

      return s0;
    }

    function peg$parseSeparator() {
      let s0;
      let s1;
      let s2;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 44) {
        s1 = peg$c193;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c194);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s1 = [s1, s2];
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c192);
        }
      }

      return s0;
    }

    function peg$parseDigit() {
      let s0;
      let s1;

      peg$silentFails++;
      if (peg$c196.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c197);
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c195);
        }
      }

      return s0;
    }

    function peg$parseNonZeroDigit() {
      let s0;
      let s1;

      peg$silentFails++;
      if (peg$c199.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c200);
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c198);
        }
      }

      return s0;
    }

    function peg$parseAlpha() {
      let s0;
      let s1;

      peg$silentFails++;
      if (peg$c202.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c203);
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c201);
        }
      }

      return s0;
    }

    function peg$parseAlphanumeric() {
      let s0;
      let s1;

      peg$silentFails++;
      if (peg$c202.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c203);
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c204);
        }
      }

      return s0;
    }

    function peg$parsePinMode() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = peg$currPos;
      if (peg$c206.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c207);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c208(s1);
      }
      s0 = s1;
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c205);
        }
      }

      return s0;
    }

    function peg$parseTrue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c209) {
        s1 = peg$c209;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c210);
        }
      }
      if (s1 === peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 49) {
          s1 = peg$c211;
          peg$currPos++;
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c212);
          }
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c213();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseFalse() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 5) === peg$c214) {
        s1 = peg$c214;
        peg$currPos += 5;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c215);
        }
      }
      if (s1 === peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 48) {
          s1 = peg$c216;
          peg$currPos++;
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c217);
          }
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c218();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseBoolean() {
      let s0;

      s0 = peg$parseTrue();
      if (s0 === peg$FAILED) {
        s0 = peg$parseFalse();
      }

      return s0;
    }

    function peg$parseInteger() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 48) {
        s1 = peg$c216;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c217);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c218();
      }
      s0 = s1;
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        s1 = peg$parseNonZeroDigit();
        if (s1 !== peg$FAILED) {
          s2 = [];
          s3 = peg$currPos;
          s4 = peg$currPos;
          peg$silentFails++;
          s5 = peg$parseSpace();
          peg$silentFails--;
          if (s5 === peg$FAILED) {
            s4 = void 0;
          } else {
            peg$currPos = s4;
            s4 = peg$FAILED;
          }
          if (s4 !== peg$FAILED) {
            s5 = peg$parseDigit();
            if (s5 !== peg$FAILED) {
              s4 = [s4, s5];
              s3 = s4;
            } else {
              peg$currPos = s3;
              s3 = peg$FAILED;
            }
          } else {
            peg$currPos = s3;
            s3 = peg$FAILED;
          }
          while (s3 !== peg$FAILED) {
            s2.push(s3);
            s3 = peg$currPos;
            s4 = peg$currPos;
            peg$silentFails++;
            s5 = peg$parseSpace();
            peg$silentFails--;
            if (s5 === peg$FAILED) {
              s4 = void 0;
            } else {
              peg$currPos = s4;
              s4 = peg$FAILED;
            }
            if (s4 !== peg$FAILED) {
              s5 = peg$parseDigit();
              if (s5 !== peg$FAILED) {
                s4 = [s4, s5];
                s3 = s4;
              } else {
                peg$currPos = s3;
                s3 = peg$FAILED;
              }
            } else {
              peg$currPos = s3;
              s3 = peg$FAILED;
            }
          }
          if (s2 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c220();
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c219);
        }
      }

      return s0;
    }

    function peg$parseSignedInteger() {
      let s0;
      let s1;
      let s2;

      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 45) {
        s1 = peg$c221;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c222);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseInteger();
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c223(s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseString() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 39) {
        s1 = peg$c225;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c226);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$currPos;
        s4 = peg$currPos;
        peg$silentFails++;
        if (input.charCodeAt(peg$currPos) === 39) {
          s5 = peg$c225;
          peg$currPos++;
        } else {
          s5 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c226);
          }
        }
        peg$silentFails--;
        if (s5 === peg$FAILED) {
          s4 = void 0;
        } else {
          peg$currPos = s4;
          s4 = peg$FAILED;
        }
        if (s4 !== peg$FAILED) {
          if (input.length > peg$currPos) {
            s5 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s5 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c227);
            }
          }
          if (s5 !== peg$FAILED) {
            s4 = [s4, s5];
            s3 = s4;
          } else {
            peg$currPos = s3;
            s3 = peg$FAILED;
          }
        } else {
          peg$currPos = s3;
          s3 = peg$FAILED;
        }
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$currPos;
          s4 = peg$currPos;
          peg$silentFails++;
          if (input.charCodeAt(peg$currPos) === 39) {
            s5 = peg$c225;
            peg$currPos++;
          } else {
            s5 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c226);
            }
          }
          peg$silentFails--;
          if (s5 === peg$FAILED) {
            s4 = void 0;
          } else {
            peg$currPos = s4;
            s4 = peg$FAILED;
          }
          if (s4 !== peg$FAILED) {
            if (input.length > peg$currPos) {
              s5 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s5 = peg$FAILED;
              if (peg$silentFails === 0) {
                peg$fail(peg$c227);
              }
            }
            if (s5 !== peg$FAILED) {
              s4 = [s4, s5];
              s3 = s4;
            } else {
              peg$currPos = s3;
              s3 = peg$FAILED;
            }
          } else {
            peg$currPos = s3;
            s3 = peg$FAILED;
          }
        }
        if (s2 !== peg$FAILED) {
          if (input.charCodeAt(peg$currPos) === 39) {
            s3 = peg$c225;
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c226);
            }
          }
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c228(s2);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c224);
        }
      }

      return s0;
    }

    function peg$parseAddress() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c183) {
        s1 = peg$c183;
        peg$currPos += 2;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c184);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseHexByte();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseHexByte();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseHexByte();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseHexByte();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c230(s2, s3, s4, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c229);
        }
      }

      return s0;
    }

    function peg$parsePin() {
      let s0;
      let s1;
      let s2;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c232) {
        s1 = peg$c232;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c233);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseDigit();
        if (s2 === peg$FAILED) {
          if (input.substr(peg$currPos, 2) === peg$c234) {
            s2 = peg$c234;
            peg$currPos += 2;
          } else {
            s2 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c235);
            }
          }
          if (s2 === peg$FAILED) {
            if (input.substr(peg$currPos, 2) === peg$c236) {
              s2 = peg$c236;
              peg$currPos += 2;
            } else {
              s2 = peg$FAILED;
              if (peg$silentFails === 0) {
                peg$fail(peg$c237);
              }
            }
            if (s2 === peg$FAILED) {
              if (input.substr(peg$currPos, 2) === peg$c238) {
                s2 = peg$c238;
                peg$currPos += 2;
              } else {
                s2 = peg$FAILED;
                if (peg$silentFails === 0) {
                  peg$fail(peg$c239);
                }
              }
              if (s2 === peg$FAILED) {
                if (input.substr(peg$currPos, 2) === peg$c240) {
                  s2 = peg$c240;
                  peg$currPos += 2;
                } else {
                  s2 = peg$FAILED;
                  if (peg$silentFails === 0) {
                    peg$fail(peg$c241);
                  }
                }
                if (s2 === peg$FAILED) {
                  if (input.substr(peg$currPos, 2) === peg$c242) {
                    s2 = peg$c242;
                    peg$currPos += 2;
                  } else {
                    s2 = peg$FAILED;
                    if (peg$silentFails === 0) {
                      peg$fail(peg$c243);
                    }
                  }
                  if (s2 === peg$FAILED) {
                    if (input.substr(peg$currPos, 2) === peg$c244) {
                      s2 = peg$c244;
                      peg$currPos += 2;
                    } else {
                      s2 = peg$FAILED;
                      if (peg$silentFails === 0) {
                        peg$fail(peg$c245);
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c246(s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c231);
        }
      }

      return s0;
    }

    function peg$parseIdentifier() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 36) {
        s1 = peg$c248;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c249);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseIdentifierChar();
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseIdentifierChar();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseIdentifierChar();
          }
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c250(s2, s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c247);
        }
      }

      return s0;
    }

    function peg$parseIdentifierChar() {
      let s0;

      s0 = peg$parseAlphanumeric();
      if (s0 === peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 36) {
          s0 = peg$c248;
          peg$currPos++;
        } else {
          s0 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c249);
          }
        }
        if (s0 === peg$FAILED) {
          if (input.charCodeAt(peg$currPos) === 95) {
            s0 = peg$c251;
            peg$currPos++;
          } else {
            s0 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c252);
            }
          }
        }
      }

      return s0;
    }

    function peg$parseIdentifierValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseIdentifier();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c253(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parsePinValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parsePin();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c254(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseBooleanValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseBoolean();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c255(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseByteValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseByte();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c256(s1);
      }
      s0 = s1;
      if (s0 === peg$FAILED) {
        s0 = peg$parsePinValue();
      }

      return s0;
    }

    function peg$parseAddressValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseAddress();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c257(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseIntegerValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseInteger();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c258(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseSignedIntegerValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseSignedInteger();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c259(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseNumberValue() {
      let s0;

      s0 = peg$parseIntegerValue();
      if (s0 === peg$FAILED) {
        s0 = peg$parseSignedIntegerValue();
      }

      return s0;
    }

    function peg$parseStringValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseString();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c260(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseValue() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = peg$parseIdentifierValue();
      if (s0 === peg$FAILED) {
        s0 = peg$parseNumberValue();
        if (s0 === peg$FAILED) {
          s0 = peg$parseAddressValue();
          if (s0 === peg$FAILED) {
            s0 = peg$parseStringValue();
            if (s0 === peg$FAILED) {
              s0 = peg$parseByteValue();
              if (s0 === peg$FAILED) {
                s0 = peg$parseBooleanValue();
              }
            }
          }
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c261);
        }
      }

      return s0;
    }

    peg$result = peg$startRuleFunction();

    if (peg$result !== peg$FAILED && peg$currPos === input.length) {
      return peg$result;
    } else {
      if (peg$result !== peg$FAILED && peg$currPos < input.length) {
        peg$fail(peg$endExpectation());
      }

      throw peg$buildStructuredError(
        peg$maxFailExpected,
        peg$maxFailPos < input.length ? input.charAt(peg$maxFailPos) : null,
        peg$maxFailPos < input.length
          ? peg$computeLocation(peg$maxFailPos, peg$maxFailPos + 1)
          : peg$computeLocation(peg$maxFailPos, peg$maxFailPos),
      );
    }
  }

  module.exports = {
    SyntaxError: peg$SyntaxError,
    parse: peg$parse,
  };
  return module.exports as peg.Parser;
}
