/* eslint-disable no-constant-condition */
import * as peg from 'pegjs';
import { InstructionNode, ValueType } from './types';

export default function (): peg.Parser {
  const module = { exports: null };
  /*
   * Generated by PEG.js 0.10.0.
   *
   * http://pegjs.org/
   */

  ('use strict');

  function peg$subclass(child, parent) {
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor();
  }

  function peg$SyntaxError(message, expected, found, location) {
    this.message = message;
    this.expected = expected;
    this.found = found;
    this.location = location;
    this.name = 'SyntaxError';

    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, peg$SyntaxError);
    }
  }

  peg$subclass(peg$SyntaxError, Error);

  peg$SyntaxError.buildMessage = function (expected, found) {
    const DESCRIBE_EXPECTATION_FNS = {
      literal: function (expectation) {
        return '"' + literalEscape(expectation.text) + '"';
      },

      class: function (expectation) {
        let escapedParts = '';
        let i;

        for (i = 0; i < expectation.parts.length; i++) {
          escapedParts +=
            expectation.parts[i] instanceof Array
              ? classEscape(expectation.parts[i][0]) + '-' + classEscape(expectation.parts[i][1])
              : classEscape(expectation.parts[i]);
        }

        return '[' + (expectation.inverted ? '^' : '') + escapedParts + ']';
      },

      any: function (expectation) {
        return 'any character';
      },

      end: function (expectation) {
        return 'end of input';
      },

      other: function (expectation) {
        return expectation.description;
      },
    };

    function hex(ch) {
      return ch.charCodeAt(0).toString(16).toUpperCase();
    }

    function literalEscape(s) {
      return s
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(/\0/g, '\\0')
        .replace(/\t/g, '\\t')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/[\x00-\x0F]/g, function (ch) {
          return '\\x0' + hex(ch);
        })
        .replace(/[\x10-\x1F\x7F-\x9F]/g, function (ch) {
          return '\\x' + hex(ch);
        });
    }

    function classEscape(s) {
      return s
        .replace(/\\/g, '\\\\')
        .replace(/\]/g, '\\]')
        .replace(/\^/g, '\\^')
        .replace(/-/g, '\\-')
        .replace(/\0/g, '\\0')
        .replace(/\t/g, '\\t')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/[\x00-\x0F]/g, function (ch) {
          return '\\x0' + hex(ch);
        })
        .replace(/[\x10-\x1F\x7F-\x9F]/g, function (ch) {
          return '\\x' + hex(ch);
        });
    }

    function describeExpectation(expectation) {
      return DESCRIBE_EXPECTATION_FNS[expectation.type](expectation);
    }

    function describeExpected(expected) {
      const descriptions = new Array(expected.length);
      let i;
      let j;

      for (i = 0; i < expected.length; i++) {
        descriptions[i] = describeExpectation(expected[i]);
      }

      descriptions.sort();

      if (descriptions.length > 0) {
        for (i = 1, j = 1; i < descriptions.length; i++) {
          if (descriptions[i - 1] !== descriptions[i]) {
            descriptions[j] = descriptions[i];
            j++;
          }
        }
        descriptions.length = j;
      }

      switch (descriptions.length) {
        case 1:
          return descriptions[0];

        case 2:
          return descriptions[0] + ' or ' + descriptions[1];

        default:
          return descriptions.slice(0, -1).join(', ') + ', or ' + descriptions[descriptions.length - 1];
      }
    }

    function describeFound(found) {
      return found ? '"' + literalEscape(found) + '"' : 'end of input';
    }

    return 'Expected ' + describeExpected(expected) + ' but ' + describeFound(found) + ' found.';
  };

  function peg$parse(input, options) {
    options = options !== void 0 ? options : {};

    const peg$FAILED = {};

    const peg$startRuleFunctions = { Program: peg$parseProgram };
    let peg$startRuleFunction = peg$parseProgram;

    const peg$c0 = function (c) {
      return c;
    };
    const peg$c1 = peg$otherExpectation('statement');
    const peg$c2 = ';';
    const peg$c3 = peg$literalExpectation(';', false);
    const peg$c4 = peg$otherExpectation('comment');
    const peg$c5 = '//';
    const peg$c6 = peg$literalExpectation('//', false);
    const peg$c7 = /^[^\n]/;
    const peg$c8 = peg$classExpectation(['\n'], true, false);
    const peg$c9 = function () {
      return InstructionNode.create('comment');
    };
    const peg$c10 = peg$otherExpectation('system instruction');
    const peg$c11 = 'halt';
    const peg$c12 = peg$literalExpectation('halt', false);
    const peg$c13 = function () {
      return InstructionNode.create('halt');
    };
    const peg$c14 = 'restart';
    const peg$c15 = peg$literalExpectation('restart', false);
    const peg$c16 = function () {
      return InstructionNode.create('restart');
    };
    const peg$c17 = 'noop';
    const peg$c18 = peg$literalExpectation('noop', false);
    const peg$c19 = function () {
      return InstructionNode.create('noop');
    };
    const peg$c20 = 'sysinfo';
    const peg$c21 = peg$literalExpectation('sysinfo', false);
    const peg$c22 = function () {
      return InstructionNode.create('sys_info');
    };
    const peg$c23 = 'dump';
    const peg$c24 = peg$literalExpectation('dump', false);
    const peg$c25 = function () {
      return InstructionNode.create('dump');
    };
    const peg$c26 = 'debug';
    const peg$c27 = peg$literalExpectation('debug', false);
    const peg$c28 = function (value) {
      return InstructionNode.create('debug', { value });
    };
    const peg$c29 = 'print';
    const peg$c30 = peg$literalExpectation('print', false);
    const peg$c31 = function (value) {
      return InstructionNode.create('print', { value });
    };
    const peg$c32 = 'delay';
    const peg$c33 = peg$literalExpectation('delay', false);
    const peg$c34 = function (value) {
      return InstructionNode.create('delay', { value });
    };
    const peg$c35 = 'sleep';
    const peg$c36 = peg$literalExpectation('sleep', false);
    const peg$c37 = function (value) {
      return InstructionNode.create('sleep', { value });
    };
    const peg$c38 = 'yield';
    const peg$c39 = peg$literalExpectation('yield', false);
    const peg$c40 = function (value) {
      return InstructionNode.create('yield', { value });
    };
    const peg$c41 = 'jump';
    const peg$c42 = peg$literalExpectation('jump', false);
    const peg$c43 = 'to';
    const peg$c44 = peg$literalExpectation('to', false);
    const peg$c45 = function (address) {
      return InstructionNode.create('jump_to', { address });
    };
    const peg$c46 = function (label) {
      return InstructionNode.create('jump_to', { label });
    };
    const peg$c47 = 'if';
    const peg$c48 = peg$literalExpectation('if', false);
    const peg$c49 = 'then';
    const peg$c50 = peg$literalExpectation('then', false);
    const peg$c51 = function (condition, label) {
      return InstructionNode.create('jump_if', { condition, label });
    };
    const peg$c52 = 'copy';
    const peg$c53 = peg$literalExpectation('copy', false);
    const peg$c54 = function (target, address) {
      return InstructionNode.create('memoryCopy', { target, address });
    };
    const peg$c55 = 'get';
    const peg$c56 = peg$literalExpectation('get', false);
    const peg$c57 = function (target, address) {
      return InstructionNode.create('memoryGet', { target, address });
    };
    const peg$c58 = 'set';
    const peg$c59 = peg$literalExpectation('set', false);
    const peg$c60 = function (target, value) {
      return InstructionNode.create('memorySet', { target, value });
    };
    const peg$c61 = '=';
    const peg$c62 = peg$literalExpectation('=', false);
    const peg$c63 = 'not';
    const peg$c64 = peg$literalExpectation('not', false);
    const peg$c65 = function (target, value) {
      return InstructionNode.create('not', { target, value });
    };
    const peg$c66 = 'inc';
    const peg$c67 = peg$literalExpectation('inc', false);
    const peg$c68 = 'dec';
    const peg$c69 = peg$literalExpectation('dec', false);
    const peg$c70 = function (operator, target) {
      return InstructionNode.create('unaryOperation', { operator, target });
    };
    const peg$c71 = function (target, a, operator, b) {
      return InstructionNode.create('binaryOperation', { operator, target, a, b });
    };
    const peg$c72 = '>=';
    const peg$c73 = peg$literalExpectation('>=', false);
    const peg$c74 = '>';
    const peg$c75 = peg$literalExpectation('>', false);
    const peg$c76 = '<=';
    const peg$c77 = peg$literalExpectation('<=', false);
    const peg$c78 = '<';
    const peg$c79 = peg$literalExpectation('<', false);
    const peg$c80 = '==';
    const peg$c81 = peg$literalExpectation('==', false);
    const peg$c82 = '!=';
    const peg$c83 = peg$literalExpectation('!=', false);
    const peg$c84 = 'xor';
    const peg$c85 = peg$literalExpectation('xor', false);
    const peg$c86 = 'and';
    const peg$c87 = peg$literalExpectation('and', false);
    const peg$c88 = 'or';
    const peg$c89 = peg$literalExpectation('or', false);
    const peg$c90 = '+';
    const peg$c91 = peg$literalExpectation('+', false);
    const peg$c92 = '-';
    const peg$c93 = peg$literalExpectation('-', false);
    const peg$c94 = '*';
    const peg$c95 = peg$literalExpectation('*', false);
    const peg$c96 = '/';
    const peg$c97 = peg$literalExpectation('/', false);
    const peg$c98 = '%';
    const peg$c99 = peg$literalExpectation('%', false);
    const peg$c100 = function (dataType, name, value) {
      return InstructionNode.create('declareIdentifier', { name, dataType, value });
    };
    const peg$c101 = function (dataType, name) {
      return InstructionNode.create('declareIdentifier', { name, dataType, value: null });
    };
    const peg$c102 = 'io write';
    const peg$c103 = peg$literalExpectation('io write', false);
    const peg$c104 = function (pin, value) {
      return InstructionNode.create('ioWrite', { pin, value });
    };
    const peg$c105 = 'io read';
    const peg$c106 = peg$literalExpectation('io read', false);
    const peg$c107 = function (target, pin) {
      return InstructionNode.create('ioRead', { pin, target });
    };
    const peg$c108 = 'io mode';
    const peg$c109 = peg$literalExpectation('io mode', false);
    const peg$c110 = function (pin, mode) {
      return InstructionNode.create('ioMode', { pin, mode });
    };
    const peg$c111 = 'io type';
    const peg$c112 = peg$literalExpectation('io type', false);
    const peg$c113 = function (pin, pinType) {
      return InstructionNode.create('ioType', { pin, pinType });
    };
    const peg$c114 = 'io allout';
    const peg$c115 = peg$literalExpectation('io allout', false);
    const peg$c116 = function () {
      return InstructionNode.create('ioAllOut');
    };
    const peg$c117 = function (value) {
      return InstructionNode.create('value', { value, dataType: ValueType.Identifier });
    };
    const peg$c118 = function (value) {
      return InstructionNode.create('value', { value, dataType: ValueType.Pin });
    };
    const peg$c119 = function (value) {
      return InstructionNode.create('value', { value, dataType: ValueType.Byte });
    };
    const peg$c120 = function (value) {
      return InstructionNode.create('value', { value, dataType: ValueType.Address });
    };
    const peg$c121 = function (value) {
      return InstructionNode.create('value', { value, dataType: ValueType.Integer });
    };
    const peg$c122 = function (value) {
      return InstructionNode.create('value', { value, dataType: ValueType.SignedInteger });
    };
    const peg$c123 = function (value) {
      return InstructionNode.create('value', { value, dataType: ValueType.String });
    };
    const peg$c124 = peg$otherExpectation('value');
    const peg$c125 = peg$otherExpectation('hexadecimal');
    const peg$c126 = /^[0-9A-Fa-f]/;
    const peg$c127 = peg$classExpectation(
      [
        ['0', '9'],
        ['A', 'F'],
        ['a', 'f'],
      ],
      false,
      false,
    );
    const peg$c128 = peg$otherExpectation('byte hex');
    const peg$c129 = function () {
      return text();
    };
    const peg$c130 = peg$otherExpectation('Byte');
    const peg$c131 = '0x';
    const peg$c132 = peg$literalExpectation('0x', false);
    const peg$c133 = function () {
      return parseInt(text(), 16);
    };
    const peg$c134 = /^[ \t]/;
    const peg$c135 = peg$classExpectation([' ', '\t'], false, false);
    const peg$c136 = peg$otherExpectation('space');
    const peg$c137 = peg$otherExpectation('new line');
    const peg$c138 = /^[\n]/;
    const peg$c139 = peg$classExpectation(['\n'], false, false);
    const peg$c140 = peg$otherExpectation('separator');
    const peg$c141 = ',';
    const peg$c142 = peg$literalExpectation(',', false);
    const peg$c143 = peg$otherExpectation('0..9');
    const peg$c144 = /^[0-9]/;
    const peg$c145 = peg$classExpectation([['0', '9']], false, false);
    const peg$c146 = peg$otherExpectation('1..9');
    const peg$c147 = /^[1-9]/;
    const peg$c148 = peg$classExpectation([['1', '9']], false, false);
    const peg$c149 = peg$otherExpectation('a-z');
    const peg$c150 = /^[a-z]/i;
    const peg$c151 = peg$classExpectation([['a', 'z']], false, true);
    const peg$c152 = peg$otherExpectation('a-z or 0-9');
    const peg$c153 = peg$otherExpectation('pin mode');
    const peg$c154 = /^[0-3]/;
    const peg$c155 = peg$classExpectation([['0', '3']], false, false);
    const peg$c156 = function (mode) {
      return Number(mode);
    };
    const peg$c157 = 'true';
    const peg$c158 = peg$literalExpectation('true', false);
    const peg$c159 = '1';
    const peg$c160 = peg$literalExpectation('1', false);
    const peg$c161 = function () {
      return 1;
    };
    const peg$c162 = 'false';
    const peg$c163 = peg$literalExpectation('false', false);
    const peg$c164 = '0';
    const peg$c165 = peg$literalExpectation('0', false);
    const peg$c166 = function () {
      return 0;
    };
    const peg$c167 = peg$otherExpectation('integer');
    const peg$c168 = function () {
      return parseInt(text());
    };
    const peg$c169 = function (int) {
      return -1 * int;
    };
    const peg$c170 = peg$otherExpectation('string');
    const peg$c171 = "'";
    const peg$c172 = peg$literalExpectation("'", false);
    const peg$c173 = peg$anyExpectation();
    const peg$c174 = function (string) {
      return string.map((s) => s[1]);
    };
    const peg$c175 = peg$otherExpectation('address');
    const peg$c176 = function (a, b, c, d) {
      return [d, c, b, a];
    };
    const peg$c177 = peg$otherExpectation('pin');
    const peg$c178 = 'pin ';
    const peg$c179 = peg$literalExpectation('pin ', false);
    const peg$c180 = '10';
    const peg$c181 = peg$literalExpectation('10', false);
    const peg$c182 = '11';
    const peg$c183 = peg$literalExpectation('11', false);
    const peg$c184 = '12';
    const peg$c185 = peg$literalExpectation('12', false);
    const peg$c186 = '13';
    const peg$c187 = peg$literalExpectation('13', false);
    const peg$c188 = '14';
    const peg$c189 = peg$literalExpectation('14', false);
    const peg$c190 = '15';
    const peg$c191 = peg$literalExpectation('15', false);
    const peg$c192 = function (pin) {
      return Number(pin);
    };
    const peg$c193 = /^[a-z]/;
    const peg$c194 = peg$classExpectation([['a', 'z']], false, false);
    const peg$c195 = /^[a-zA-Z0-9_]/;
    const peg$c196 = peg$classExpectation([['a', 'z'], ['A', 'Z'], ['0', '9'], '_'], false, false);
    const peg$c197 = '@';
    const peg$c198 = peg$literalExpectation('@', false);
    const peg$c199 = function (label) {
      return InstructionNode.create('label', { label });
    };
    const peg$c200 = peg$otherExpectation('identifier');
    const peg$c201 = '$';
    const peg$c202 = peg$literalExpectation('$', false);
    const peg$c203 = function (head, tail) {
      return text();
    };
    const peg$c204 = '_';
    const peg$c205 = peg$literalExpectation('_', false);
    const peg$c206 = function (name) {
      return InstructionNode.create('useIdentifier', { name });
    };
    const peg$c207 = 'byte';
    const peg$c208 = peg$literalExpectation('byte', false);
    const peg$c209 = function () {
      return ValueType.Byte;
    };
    const peg$c210 = 'address';
    const peg$c211 = peg$literalExpectation('address', false);
    const peg$c212 = function () {
      return ValueType.Address;
    };
    const peg$c213 = 'uint';
    const peg$c214 = peg$literalExpectation('uint', false);
    const peg$c215 = function () {
      return ValueType.Integer;
    };
    const peg$c216 = 'int';
    const peg$c217 = peg$literalExpectation('int', false);
    const peg$c218 = function () {
      return ValueType.SignedInteger;
    };
    const peg$c219 = 'string';
    const peg$c220 = peg$literalExpectation('string', false);
    const peg$c221 = function () {
      return ValueType.String;
    };

    let peg$currPos = 0;
    let peg$savedPos = 0;
    const peg$posDetailsCache = [{ line: 1, column: 1 }];
    let peg$maxFailPos = 0;
    let peg$maxFailExpected = [];
    let peg$silentFails = 0;

    let peg$result;

    if ('startRule' in options) {
      if (!(options.startRule in peg$startRuleFunctions)) {
        throw new Error('Can\'t start parsing from rule "' + options.startRule + '".');
      }

      peg$startRuleFunction = peg$startRuleFunctions[options.startRule];
    }

    function text() {
      return input.substring(peg$savedPos, peg$currPos);
    }

    function location() {
      return peg$computeLocation(peg$savedPos, peg$currPos);
    }

    function expected(description, location) {
      location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos);

      throw peg$buildStructuredError(
        [peg$otherExpectation(description)],
        input.substring(peg$savedPos, peg$currPos),
        location,
      );
    }

    function error(message, location) {
      location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos);

      throw peg$buildSimpleError(message, location);
    }

    function peg$literalExpectation(text, ignoreCase) {
      return { type: 'literal', text: text, ignoreCase: ignoreCase };
    }

    function peg$classExpectation(parts, inverted, ignoreCase) {
      return { type: 'class', parts: parts, inverted: inverted, ignoreCase: ignoreCase };
    }

    function peg$anyExpectation() {
      return { type: 'any' };
    }

    function peg$endExpectation() {
      return { type: 'end' };
    }

    function peg$otherExpectation(description) {
      return { type: 'other', description: description };
    }

    function peg$computePosDetails(pos) {
      let details = peg$posDetailsCache[pos];
      let p;

      if (details) {
        return details;
      } else {
        p = pos - 1;
        while (!peg$posDetailsCache[p]) {
          p--;
        }

        details = peg$posDetailsCache[p];
        details = {
          line: details.line,
          column: details.column,
        };

        while (p < pos) {
          if (input.charCodeAt(p) === 10) {
            details.line++;
            details.column = 1;
          } else {
            details.column++;
          }

          p++;
        }

        peg$posDetailsCache[pos] = details;
        return details;
      }
    }

    function peg$computeLocation(startPos, endPos) {
      const startPosDetails = peg$computePosDetails(startPos);
      const endPosDetails = peg$computePosDetails(endPos);

      return {
        start: {
          offset: startPos,
          line: startPosDetails.line,
          column: startPosDetails.column,
        },
        end: {
          offset: endPos,
          line: endPosDetails.line,
          column: endPosDetails.column,
        },
      };
    }

    function peg$fail(expected) {
      if (peg$currPos < peg$maxFailPos) {
        return;
      }

      if (peg$currPos > peg$maxFailPos) {
        peg$maxFailPos = peg$currPos;
        peg$maxFailExpected = [];
      }

      peg$maxFailExpected.push(expected);
    }

    function peg$buildSimpleError(message, location) {
      return new peg$SyntaxError(message, null, null, location);
    }

    function peg$buildStructuredError(expected, found, location) {
      return new peg$SyntaxError(peg$SyntaxError.buildMessage(expected, found), expected, found, location);
    }

    function peg$parseProgram() {
      let s0;
      let s1;
      let s2;

      s0 = peg$currPos;
      s1 = [];
      s2 = peg$parseLine();
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        s2 = peg$parseLine();
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c0(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseLine() {
      let s0;
      let s1;
      let s2;
      let s3;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parseSpaces();
      if (s1 !== peg$FAILED) {
        s2 = peg$parseStatement();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseStatementSeparator();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c0(s2);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c1);
        }
      }

      return s0;
    }

    function peg$parseStatementSeparator() {
      let s0;

      s0 = peg$parseNewLine();
      if (s0 === peg$FAILED) {
        s0 = null;
      }
      if (s0 === peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 59) {
          s0 = peg$c2;
          peg$currPos++;
        } else {
          s0 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c3);
          }
        }
        if (s0 === peg$FAILED) {
          s0 = null;
        }
      }

      return s0;
    }

    function peg$parseStatement() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = peg$parseDefineLabel();
      if (s0 === peg$FAILED) {
        s0 = peg$parseSystemInstruction();
        if (s0 === peg$FAILED) {
          s0 = peg$parseMemoryInstruction();
          if (s0 === peg$FAILED) {
            s0 = peg$parseOperator();
            if (s0 === peg$FAILED) {
              s0 = peg$parseIoInstruction();
              if (s0 === peg$FAILED) {
                s0 = peg$parseComment();
              }
            }
          }
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c1);
        }
      }

      return s0;
    }

    function peg$parseComment() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c5) {
        s2 = peg$c5;
        peg$currPos += 2;
      } else {
        s2 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c6);
        }
      }
      if (s2 !== peg$FAILED) {
        s3 = [];
        if (peg$c7.test(input.charAt(peg$currPos))) {
          s4 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s4 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c8);
          }
        }
        if (s4 !== peg$FAILED) {
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            if (peg$c7.test(input.charAt(peg$currPos))) {
              s4 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s4 = peg$FAILED;
              if (peg$silentFails === 0) {
                peg$fail(peg$c8);
              }
            }
          }
        } else {
          s3 = peg$FAILED;
        }
        if (s3 !== peg$FAILED) {
          s2 = [s2, s3];
          s1 = s2;
        } else {
          peg$currPos = s1;
          s1 = peg$FAILED;
        }
      } else {
        peg$currPos = s1;
        s1 = peg$FAILED;
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c9();
      }
      s0 = s1;
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c4);
        }
      }

      return s0;
    }

    function peg$parseSystemInstruction() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = peg$parsehalt();
      if (s0 === peg$FAILED) {
        s0 = peg$parserestart();
        if (s0 === peg$FAILED) {
          s0 = peg$parsesysinfo();
          if (s0 === peg$FAILED) {
            s0 = peg$parsedebug();
            if (s0 === peg$FAILED) {
              s0 = peg$parsedump();
              if (s0 === peg$FAILED) {
                s0 = peg$parsenoop();
                if (s0 === peg$FAILED) {
                  s0 = peg$parseprint();
                  if (s0 === peg$FAILED) {
                    s0 = peg$parsejump_to();
                    if (s0 === peg$FAILED) {
                      s0 = peg$parsejump_if();
                      if (s0 === peg$FAILED) {
                        s0 = peg$parsedelay();
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c10);
        }
      }

      return s0;
    }

    function peg$parsehalt() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c11) {
        s1 = peg$c11;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c12);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c13();
      }
      s0 = s1;

      return s0;
    }

    function peg$parserestart() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c14) {
        s1 = peg$c14;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c15);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c16();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsenoop() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c17) {
        s1 = peg$c17;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c18);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c19();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsesysinfo() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c20) {
        s1 = peg$c20;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c21);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c22();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsedump() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c23) {
        s1 = peg$c23;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c24);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c25();
      }
      s0 = s1;

      return s0;
    }

    function peg$parsedebug() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 5) === peg$c26) {
        s1 = peg$c26;
        peg$currPos += 5;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c27);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseBoolean();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c28(s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseprint() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 5) === peg$c29) {
        s1 = peg$c29;
        peg$currPos += 5;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c30);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseValue();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c31(s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsedelay() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 5) === peg$c32) {
        s1 = peg$c32;
        peg$currPos += 5;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c33);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseIntegerValue();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c34(s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        if (input.substr(peg$currPos, 5) === peg$c35) {
          s1 = peg$c35;
          peg$currPos += 5;
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c36);
          }
        }
        if (s1 !== peg$FAILED) {
          s2 = peg$parseSpaces();
          if (s2 !== peg$FAILED) {
            s3 = peg$parseIntegerValue();
            if (s3 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c37(s3);
              s0 = s1;
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
        if (s0 === peg$FAILED) {
          s0 = peg$currPos;
          if (input.substr(peg$currPos, 5) === peg$c38) {
            s1 = peg$c38;
            peg$currPos += 5;
          } else {
            s1 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c39);
            }
          }
          if (s1 !== peg$FAILED) {
            s2 = peg$parseSpaces();
            if (s2 !== peg$FAILED) {
              s3 = peg$parseIntegerValue();
              if (s3 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c40(s3);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        }
      }

      return s0;
    }

    function peg$parsejump_to() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c41) {
        s1 = peg$c41;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c42);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          if (input.substr(peg$currPos, 2) === peg$c43) {
            s3 = peg$c43;
            peg$currPos += 2;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c44);
            }
          }
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSpaces();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseAddressValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c45(s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        if (input.substr(peg$currPos, 4) === peg$c41) {
          s1 = peg$c41;
          peg$currPos += 4;
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c42);
          }
        }
        if (s1 !== peg$FAILED) {
          s2 = peg$parseSpaces();
          if (s2 !== peg$FAILED) {
            if (input.substr(peg$currPos, 2) === peg$c43) {
              s3 = peg$c43;
              peg$currPos += 2;
            } else {
              s3 = peg$FAILED;
              if (peg$silentFails === 0) {
                peg$fail(peg$c44);
              }
            }
            if (s3 !== peg$FAILED) {
              s4 = peg$parseSpaces();
              if (s4 !== peg$FAILED) {
                s5 = peg$parseLabel();
                if (s5 !== peg$FAILED) {
                  peg$savedPos = s0;
                  s1 = peg$c46(s5);
                  s0 = s1;
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      }

      return s0;
    }

    function peg$parsejump_if() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;
      let s6;
      let s7;
      let s8;
      let s9;
      let s10;
      let s11;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c47) {
        s1 = peg$c47;
        peg$currPos += 2;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c48);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseValue();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSpaces();
            if (s4 !== peg$FAILED) {
              if (input.substr(peg$currPos, 4) === peg$c49) {
                s5 = peg$c49;
                peg$currPos += 4;
              } else {
                s5 = peg$FAILED;
                if (peg$silentFails === 0) {
                  peg$fail(peg$c50);
                }
              }
              if (s5 !== peg$FAILED) {
                s6 = peg$parseSpaces();
                if (s6 !== peg$FAILED) {
                  if (input.substr(peg$currPos, 4) === peg$c41) {
                    s7 = peg$c41;
                    peg$currPos += 4;
                  } else {
                    s7 = peg$FAILED;
                    if (peg$silentFails === 0) {
                      peg$fail(peg$c42);
                    }
                  }
                  if (s7 !== peg$FAILED) {
                    s8 = peg$parseSpaces();
                    if (s8 !== peg$FAILED) {
                      if (input.substr(peg$currPos, 2) === peg$c43) {
                        s9 = peg$c43;
                        peg$currPos += 2;
                      } else {
                        s9 = peg$FAILED;
                        if (peg$silentFails === 0) {
                          peg$fail(peg$c44);
                        }
                      }
                      if (s9 !== peg$FAILED) {
                        s10 = peg$parseSpaces();
                        if (s10 !== peg$FAILED) {
                          s11 = peg$parseLabel();
                          if (s11 !== peg$FAILED) {
                            peg$savedPos = s0;
                            s1 = peg$c51(s3, s11);
                            s0 = s1;
                          } else {
                            peg$currPos = s0;
                            s0 = peg$FAILED;
                          }
                        } else {
                          peg$currPos = s0;
                          s0 = peg$FAILED;
                        }
                      } else {
                        peg$currPos = s0;
                        s0 = peg$FAILED;
                      }
                    } else {
                      peg$currPos = s0;
                      s0 = peg$FAILED;
                    }
                  } else {
                    peg$currPos = s0;
                    s0 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseMemoryInstruction() {
      let s0;

      s0 = peg$parseMemoryGet();
      if (s0 === peg$FAILED) {
        s0 = peg$parseMemorySet();
        if (s0 === peg$FAILED) {
          s0 = peg$parseMemoryCopy();
        }
      }

      return s0;
    }

    function peg$parseMemoryCopy() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c52) {
        s1 = peg$c52;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c53);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseAddressValue();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseAddressValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c54(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseMemoryGet() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c55) {
        s1 = peg$c55;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c56);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseIdentifierValue();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseAddressValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c57(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseMemorySet() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c58) {
        s1 = peg$c58;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c59);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseAddressValue();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c60(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseOperator() {
      let s0;

      s0 = peg$parseunary_operation();
      if (s0 === peg$FAILED) {
        s0 = peg$parsebinary_operation();
        if (s0 === peg$FAILED) {
          s0 = peg$parsedeclare_identifier();
        }
      }

      return s0;
    }

    function peg$parseASSIGN() {
      let s0;

      if (input.charCodeAt(peg$currPos) === 61) {
        s0 = peg$c61;
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c62);
        }
      }

      return s0;
    }

    function peg$parseunary_operation() {
      let s0;

      s0 = peg$parsenot();
      if (s0 === peg$FAILED) {
        s0 = peg$parsestep();
      }

      return s0;
    }

    function peg$parsenot() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c63) {
        s1 = peg$c63;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c64);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseIdentifierValue();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c65(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsestep() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 3) === peg$c66) {
        s1 = peg$c66;
        peg$currPos += 3;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c67);
        }
      }
      if (s1 === peg$FAILED) {
        if (input.substr(peg$currPos, 3) === peg$c68) {
          s1 = peg$c68;
          peg$currPos += 3;
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c69);
          }
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseIdentifierValue();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c70(s1, s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsebinary_operation() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;
      let s6;
      let s7;
      let s8;
      let s9;

      s0 = peg$currPos;
      s1 = peg$parseIdentifierValue();
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseASSIGN();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSpaces();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseValue();
              if (s5 !== peg$FAILED) {
                s6 = peg$parseSpaces();
                if (s6 !== peg$FAILED) {
                  s7 = peg$parsebinary_operator();
                  if (s7 !== peg$FAILED) {
                    s8 = peg$parseSpaces();
                    if (s8 !== peg$FAILED) {
                      s9 = peg$parseValue();
                      if (s9 !== peg$FAILED) {
                        peg$savedPos = s0;
                        s1 = peg$c71(s1, s5, s7, s9);
                        s0 = s1;
                      } else {
                        peg$currPos = s0;
                        s0 = peg$FAILED;
                      }
                    } else {
                      peg$currPos = s0;
                      s0 = peg$FAILED;
                    }
                  } else {
                    peg$currPos = s0;
                    s0 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parsebinary_operator() {
      let s0;

      if (input.substr(peg$currPos, 2) === peg$c72) {
        s0 = peg$c72;
        peg$currPos += 2;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c73);
        }
      }
      if (s0 === peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 62) {
          s0 = peg$c74;
          peg$currPos++;
        } else {
          s0 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c75);
          }
        }
        if (s0 === peg$FAILED) {
          if (input.substr(peg$currPos, 2) === peg$c76) {
            s0 = peg$c76;
            peg$currPos += 2;
          } else {
            s0 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c77);
            }
          }
          if (s0 === peg$FAILED) {
            if (input.charCodeAt(peg$currPos) === 60) {
              s0 = peg$c78;
              peg$currPos++;
            } else {
              s0 = peg$FAILED;
              if (peg$silentFails === 0) {
                peg$fail(peg$c79);
              }
            }
            if (s0 === peg$FAILED) {
              if (input.substr(peg$currPos, 2) === peg$c80) {
                s0 = peg$c80;
                peg$currPos += 2;
              } else {
                s0 = peg$FAILED;
                if (peg$silentFails === 0) {
                  peg$fail(peg$c81);
                }
              }
              if (s0 === peg$FAILED) {
                if (input.substr(peg$currPos, 2) === peg$c82) {
                  s0 = peg$c82;
                  peg$currPos += 2;
                } else {
                  s0 = peg$FAILED;
                  if (peg$silentFails === 0) {
                    peg$fail(peg$c83);
                  }
                }
                if (s0 === peg$FAILED) {
                  if (input.substr(peg$currPos, 3) === peg$c84) {
                    s0 = peg$c84;
                    peg$currPos += 3;
                  } else {
                    s0 = peg$FAILED;
                    if (peg$silentFails === 0) {
                      peg$fail(peg$c85);
                    }
                  }
                  if (s0 === peg$FAILED) {
                    if (input.substr(peg$currPos, 3) === peg$c86) {
                      s0 = peg$c86;
                      peg$currPos += 3;
                    } else {
                      s0 = peg$FAILED;
                      if (peg$silentFails === 0) {
                        peg$fail(peg$c87);
                      }
                    }
                    if (s0 === peg$FAILED) {
                      if (input.substr(peg$currPos, 2) === peg$c88) {
                        s0 = peg$c88;
                        peg$currPos += 2;
                      } else {
                        s0 = peg$FAILED;
                        if (peg$silentFails === 0) {
                          peg$fail(peg$c89);
                        }
                      }
                      if (s0 === peg$FAILED) {
                        if (input.charCodeAt(peg$currPos) === 43) {
                          s0 = peg$c90;
                          peg$currPos++;
                        } else {
                          s0 = peg$FAILED;
                          if (peg$silentFails === 0) {
                            peg$fail(peg$c91);
                          }
                        }
                        if (s0 === peg$FAILED) {
                          if (input.charCodeAt(peg$currPos) === 45) {
                            s0 = peg$c92;
                            peg$currPos++;
                          } else {
                            s0 = peg$FAILED;
                            if (peg$silentFails === 0) {
                              peg$fail(peg$c93);
                            }
                          }
                          if (s0 === peg$FAILED) {
                            if (input.charCodeAt(peg$currPos) === 42) {
                              s0 = peg$c94;
                              peg$currPos++;
                            } else {
                              s0 = peg$FAILED;
                              if (peg$silentFails === 0) {
                                peg$fail(peg$c95);
                              }
                            }
                            if (s0 === peg$FAILED) {
                              if (input.charCodeAt(peg$currPos) === 47) {
                                s0 = peg$c96;
                                peg$currPos++;
                              } else {
                                s0 = peg$FAILED;
                                if (peg$silentFails === 0) {
                                  peg$fail(peg$c97);
                                }
                              }
                              if (s0 === peg$FAILED) {
                                if (input.charCodeAt(peg$currPos) === 37) {
                                  s0 = peg$c98;
                                  peg$currPos++;
                                } else {
                                  s0 = peg$FAILED;
                                  if (peg$silentFails === 0) {
                                    peg$fail(peg$c99);
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }

      return s0;
    }

    function peg$parsedeclare_identifier() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;
      let s6;
      let s7;

      s0 = peg$currPos;
      s1 = peg$parseValueTypeMap();
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseIdentifier();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSpaces();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseASSIGN();
              if (s5 !== peg$FAILED) {
                s6 = peg$parseSpaces();
                if (s6 !== peg$FAILED) {
                  s7 = peg$parseValue();
                  if (s7 !== peg$FAILED) {
                    peg$savedPos = s0;
                    s1 = peg$c100(s1, s3, s7);
                    s0 = s1;
                  } else {
                    peg$currPos = s0;
                    s0 = peg$FAILED;
                  }
                } else {
                  peg$currPos = s0;
                  s0 = peg$FAILED;
                }
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        s1 = peg$parseValueTypeMap();
        if (s1 !== peg$FAILED) {
          s2 = peg$parseSpaces();
          if (s2 !== peg$FAILED) {
            s3 = peg$parseIdentifier();
            if (s3 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c101(s1, s3);
              s0 = s1;
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      }

      return s0;
    }

    function peg$parseIoInstruction() {
      let s0;

      s0 = peg$parseIoWrite();
      if (s0 === peg$FAILED) {
        s0 = peg$parseIoRead();
        if (s0 === peg$FAILED) {
          s0 = peg$parseIoMode();
          if (s0 === peg$FAILED) {
            s0 = peg$parseIoType();
            if (s0 === peg$FAILED) {
              s0 = peg$parseIoAllOut();
            }
          }
        }
      }

      return s0;
    }

    function peg$parseIoWrite() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 8) === peg$c102) {
        s1 = peg$c102;
        peg$currPos += 8;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c103);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parsePin();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseIoValue();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c104(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseIoRead() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c105) {
        s1 = peg$c105;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c106);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseIdentifierValue();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parsePin();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c107(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseIoMode() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c108) {
        s1 = peg$c108;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c109);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parsePin();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parsePinMode();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c110(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseIoType() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c111) {
        s1 = peg$c111;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c112);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parsePin();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseSeparator();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseDigit();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c113(s3, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseIoAllOut() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 9) === peg$c114) {
        s1 = peg$c114;
        peg$currPos += 9;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c115);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c116();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseIoValue() {
      let s0;

      s0 = peg$parseByteValue();
      if (s0 === peg$FAILED) {
        s0 = peg$parseIdentifierValue();
        if (s0 === peg$FAILED) {
          s0 = peg$parseBooleanValue();
        }
      }

      return s0;
    }

    function peg$parseIdentifierValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseUseIdentifier();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c117(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parsePinValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parsePin();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c118(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseBooleanValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseBoolean();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c119(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseByteValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseByte();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c119(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseAddressValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseAddress();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c120(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseIntegerValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseInteger();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c121(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseSignedIntegerValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseSignedInteger();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c122(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseStringValue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseString();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c123(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseNumberValue() {
      let s0;

      s0 = peg$parseIntegerValue();
      if (s0 === peg$FAILED) {
        s0 = peg$parseSignedIntegerValue();
      }

      return s0;
    }

    function peg$parseValue() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = peg$parseIdentifierValue();
      if (s0 === peg$FAILED) {
        s0 = peg$parseNumberValue();
        if (s0 === peg$FAILED) {
          s0 = peg$parseAddressValue();
          if (s0 === peg$FAILED) {
            s0 = peg$parseStringValue();
            if (s0 === peg$FAILED) {
              s0 = peg$parseByteValue();
              if (s0 === peg$FAILED) {
                s0 = peg$parseBooleanValue();
              }
            }
          }
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c124);
        }
      }

      return s0;
    }

    function peg$parseHexDigit() {
      let s0;
      let s1;

      peg$silentFails++;
      if (peg$c126.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c127);
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c125);
        }
      }

      return s0;
    }

    function peg$parseHexByte() {
      let s0;
      let s1;
      let s2;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parseHexDigit();
      if (s1 !== peg$FAILED) {
        s2 = peg$parseHexDigit();
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c129();
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c128);
        }
      }

      return s0;
    }

    function peg$parseByte() {
      let s0;
      let s1;
      let s2;
      let s3;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c131) {
        s1 = peg$c131;
        peg$currPos += 2;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c132);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseHexDigit();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseHexDigit();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c133();
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c130);
        }
      }

      return s0;
    }

    function peg$parseSpace() {
      let s0;

      if (peg$c134.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c135);
        }
      }

      return s0;
    }

    function peg$parseSpaces() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = [];
      s1 = peg$parseSpace();
      while (s1 !== peg$FAILED) {
        s0.push(s1);
        s1 = peg$parseSpace();
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c136);
        }
      }

      return s0;
    }

    function peg$parseNewLine() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = [];
      if (peg$c138.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c139);
        }
      }
      if (s1 !== peg$FAILED) {
        while (s1 !== peg$FAILED) {
          s0.push(s1);
          if (peg$c138.test(input.charAt(peg$currPos))) {
            s1 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s1 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c139);
            }
          }
        }
      } else {
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c137);
        }
      }

      return s0;
    }

    function peg$parseSeparator() {
      let s0;
      let s1;
      let s2;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 44) {
        s1 = peg$c141;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c142);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s1 = [s1, s2];
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c140);
        }
      }

      return s0;
    }

    function peg$parseDigit() {
      let s0;
      let s1;

      peg$silentFails++;
      if (peg$c144.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c145);
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c143);
        }
      }

      return s0;
    }

    function peg$parseNonZeroDigit() {
      let s0;
      let s1;

      peg$silentFails++;
      if (peg$c147.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c148);
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c146);
        }
      }

      return s0;
    }

    function peg$parseAlpha() {
      let s0;
      let s1;

      peg$silentFails++;
      if (peg$c150.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c151);
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c149);
        }
      }

      return s0;
    }

    function peg$parseAlphanumeric() {
      let s0;
      let s1;

      peg$silentFails++;
      if (peg$c150.test(input.charAt(peg$currPos))) {
        s0 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c151);
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c152);
        }
      }

      return s0;
    }

    function peg$parsePinMode() {
      let s0;
      let s1;

      peg$silentFails++;
      s0 = peg$currPos;
      if (peg$c154.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c155);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c156(s1);
      }
      s0 = s1;
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c153);
        }
      }

      return s0;
    }

    function peg$parseTrue() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c157) {
        s1 = peg$c157;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c158);
        }
      }
      if (s1 === peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 49) {
          s1 = peg$c159;
          peg$currPos++;
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c160);
          }
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c161();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseFalse() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 5) === peg$c162) {
        s1 = peg$c162;
        peg$currPos += 5;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c163);
        }
      }
      if (s1 === peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 48) {
          s1 = peg$c164;
          peg$currPos++;
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c165);
          }
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c166();
      }
      s0 = s1;

      return s0;
    }

    function peg$parseBoolean() {
      let s0;

      s0 = peg$parseTrue();
      if (s0 === peg$FAILED) {
        s0 = peg$parseFalse();
      }

      return s0;
    }

    function peg$parseInteger() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 48) {
        s1 = peg$c164;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c165);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c166();
      }
      s0 = s1;
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        s1 = peg$parseNonZeroDigit();
        if (s1 !== peg$FAILED) {
          s2 = [];
          s3 = peg$currPos;
          s4 = peg$currPos;
          peg$silentFails++;
          s5 = peg$parseSpace();
          peg$silentFails--;
          if (s5 === peg$FAILED) {
            s4 = void 0;
          } else {
            peg$currPos = s4;
            s4 = peg$FAILED;
          }
          if (s4 !== peg$FAILED) {
            s5 = peg$parseDigit();
            if (s5 !== peg$FAILED) {
              s4 = [s4, s5];
              s3 = s4;
            } else {
              peg$currPos = s3;
              s3 = peg$FAILED;
            }
          } else {
            peg$currPos = s3;
            s3 = peg$FAILED;
          }
          while (s3 !== peg$FAILED) {
            s2.push(s3);
            s3 = peg$currPos;
            s4 = peg$currPos;
            peg$silentFails++;
            s5 = peg$parseSpace();
            peg$silentFails--;
            if (s5 === peg$FAILED) {
              s4 = void 0;
            } else {
              peg$currPos = s4;
              s4 = peg$FAILED;
            }
            if (s4 !== peg$FAILED) {
              s5 = peg$parseDigit();
              if (s5 !== peg$FAILED) {
                s4 = [s4, s5];
                s3 = s4;
              } else {
                peg$currPos = s3;
                s3 = peg$FAILED;
              }
            } else {
              peg$currPos = s3;
              s3 = peg$FAILED;
            }
          }
          if (s2 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c168();
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c167);
        }
      }

      return s0;
    }

    function peg$parseSignedInteger() {
      let s0;
      let s1;
      let s2;

      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 45) {
        s1 = peg$c92;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c93);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseInteger();
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c169(s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseString() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 39) {
        s1 = peg$c171;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c172);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$currPos;
        s4 = peg$currPos;
        peg$silentFails++;
        if (input.charCodeAt(peg$currPos) === 39) {
          s5 = peg$c171;
          peg$currPos++;
        } else {
          s5 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c172);
          }
        }
        peg$silentFails--;
        if (s5 === peg$FAILED) {
          s4 = void 0;
        } else {
          peg$currPos = s4;
          s4 = peg$FAILED;
        }
        if (s4 !== peg$FAILED) {
          if (input.length > peg$currPos) {
            s5 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s5 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c173);
            }
          }
          if (s5 !== peg$FAILED) {
            s4 = [s4, s5];
            s3 = s4;
          } else {
            peg$currPos = s3;
            s3 = peg$FAILED;
          }
        } else {
          peg$currPos = s3;
          s3 = peg$FAILED;
        }
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$currPos;
          s4 = peg$currPos;
          peg$silentFails++;
          if (input.charCodeAt(peg$currPos) === 39) {
            s5 = peg$c171;
            peg$currPos++;
          } else {
            s5 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c172);
            }
          }
          peg$silentFails--;
          if (s5 === peg$FAILED) {
            s4 = void 0;
          } else {
            peg$currPos = s4;
            s4 = peg$FAILED;
          }
          if (s4 !== peg$FAILED) {
            if (input.length > peg$currPos) {
              s5 = input.charAt(peg$currPos);
              peg$currPos++;
            } else {
              s5 = peg$FAILED;
              if (peg$silentFails === 0) {
                peg$fail(peg$c173);
              }
            }
            if (s5 !== peg$FAILED) {
              s4 = [s4, s5];
              s3 = s4;
            } else {
              peg$currPos = s3;
              s3 = peg$FAILED;
            }
          } else {
            peg$currPos = s3;
            s3 = peg$FAILED;
          }
        }
        if (s2 !== peg$FAILED) {
          if (input.charCodeAt(peg$currPos) === 39) {
            s3 = peg$c171;
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c172);
            }
          }
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c174(s2);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c170);
        }
      }

      return s0;
    }

    function peg$parseAddress() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;
      let s5;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.substr(peg$currPos, 2) === peg$c131) {
        s1 = peg$c131;
        peg$currPos += 2;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c132);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseHexByte();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseHexByte();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseHexByte();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseHexByte();
              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c176(s2, s3, s4, s5);
                s0 = s1;
              } else {
                peg$currPos = s0;
                s0 = peg$FAILED;
              }
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c175);
        }
      }

      return s0;
    }

    function peg$parsePin() {
      let s0;
      let s1;
      let s2;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c178) {
        s1 = peg$c178;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c179);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseDigit();
        if (s2 === peg$FAILED) {
          if (input.substr(peg$currPos, 2) === peg$c180) {
            s2 = peg$c180;
            peg$currPos += 2;
          } else {
            s2 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c181);
            }
          }
          if (s2 === peg$FAILED) {
            if (input.substr(peg$currPos, 2) === peg$c182) {
              s2 = peg$c182;
              peg$currPos += 2;
            } else {
              s2 = peg$FAILED;
              if (peg$silentFails === 0) {
                peg$fail(peg$c183);
              }
            }
            if (s2 === peg$FAILED) {
              if (input.substr(peg$currPos, 2) === peg$c184) {
                s2 = peg$c184;
                peg$currPos += 2;
              } else {
                s2 = peg$FAILED;
                if (peg$silentFails === 0) {
                  peg$fail(peg$c185);
                }
              }
              if (s2 === peg$FAILED) {
                if (input.substr(peg$currPos, 2) === peg$c186) {
                  s2 = peg$c186;
                  peg$currPos += 2;
                } else {
                  s2 = peg$FAILED;
                  if (peg$silentFails === 0) {
                    peg$fail(peg$c187);
                  }
                }
                if (s2 === peg$FAILED) {
                  if (input.substr(peg$currPos, 2) === peg$c188) {
                    s2 = peg$c188;
                    peg$currPos += 2;
                  } else {
                    s2 = peg$FAILED;
                    if (peg$silentFails === 0) {
                      peg$fail(peg$c189);
                    }
                  }
                  if (s2 === peg$FAILED) {
                    if (input.substr(peg$currPos, 2) === peg$c190) {
                      s2 = peg$c190;
                      peg$currPos += 2;
                    } else {
                      s2 = peg$FAILED;
                      if (peg$silentFails === 0) {
                        peg$fail(peg$c191);
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c192(s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c177);
        }
      }

      return s0;
    }

    function peg$parseLabelText() {
      let s0;
      let s1;
      let s2;
      let s3;

      s0 = peg$currPos;
      if (peg$c193.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c194);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c195.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c196);
          }
        }
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c195.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c196);
            }
          }
        }
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c129();
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseDefineLabel() {
      let s0;
      let s1;
      let s2;

      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 64) {
        s1 = peg$c197;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c198);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseLabelText();
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c199(s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }

      return s0;
    }

    function peg$parseLabel() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseLabelText();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c199(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseIdentifier() {
      let s0;
      let s1;
      let s2;
      let s3;
      let s4;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 36) {
        s1 = peg$c201;
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c202);
        }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseIdentifierChar();
        if (s2 !== peg$FAILED) {
          s3 = [];
          s4 = peg$parseIdentifierChar();
          while (s4 !== peg$FAILED) {
            s3.push(s4);
            s4 = peg$parseIdentifierChar();
          }
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c203(s2, s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c200);
        }
      }

      return s0;
    }

    function peg$parseIdentifierChar() {
      let s0;

      s0 = peg$parseAlphanumeric();
      if (s0 === peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 36) {
          s0 = peg$c201;
          peg$currPos++;
        } else {
          s0 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c202);
          }
        }
        if (s0 === peg$FAILED) {
          if (input.charCodeAt(peg$currPos) === 95) {
            s0 = peg$c204;
            peg$currPos++;
          } else {
            s0 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c205);
            }
          }
        }
      }

      return s0;
    }

    function peg$parseUseIdentifier() {
      let s0;
      let s1;

      s0 = peg$currPos;
      s1 = peg$parseIdentifier();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c206(s1);
      }
      s0 = s1;

      return s0;
    }

    function peg$parseValueTypeMap() {
      let s0;
      let s1;

      s0 = peg$currPos;
      if (input.substr(peg$currPos, 4) === peg$c207) {
        s1 = peg$c207;
        peg$currPos += 4;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {
          peg$fail(peg$c208);
        }
      }
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c209();
      }
      s0 = s1;
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        if (input.substr(peg$currPos, 7) === peg$c210) {
          s1 = peg$c210;
          peg$currPos += 7;
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {
            peg$fail(peg$c211);
          }
        }
        if (s1 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c212();
        }
        s0 = s1;
        if (s0 === peg$FAILED) {
          s0 = peg$currPos;
          if (input.substr(peg$currPos, 4) === peg$c213) {
            s1 = peg$c213;
            peg$currPos += 4;
          } else {
            s1 = peg$FAILED;
            if (peg$silentFails === 0) {
              peg$fail(peg$c214);
            }
          }
          if (s1 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c215();
          }
          s0 = s1;
          if (s0 === peg$FAILED) {
            s0 = peg$currPos;
            if (input.substr(peg$currPos, 3) === peg$c216) {
              s1 = peg$c216;
              peg$currPos += 3;
            } else {
              s1 = peg$FAILED;
              if (peg$silentFails === 0) {
                peg$fail(peg$c217);
              }
            }
            if (s1 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c218();
            }
            s0 = s1;
            if (s0 === peg$FAILED) {
              s0 = peg$currPos;
              if (input.substr(peg$currPos, 6) === peg$c219) {
                s1 = peg$c219;
                peg$currPos += 6;
              } else {
                s1 = peg$FAILED;
                if (peg$silentFails === 0) {
                  peg$fail(peg$c220);
                }
              }
              if (s1 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c221();
              }
              s0 = s1;
            }
          }
        }
      }

      return s0;
    }

    peg$result = peg$startRuleFunction();

    if (peg$result !== peg$FAILED && peg$currPos === input.length) {
      return peg$result;
    } else {
      if (peg$result !== peg$FAILED && peg$currPos < input.length) {
        peg$fail(peg$endExpectation());
      }

      throw peg$buildStructuredError(
        peg$maxFailExpected,
        peg$maxFailPos < input.length ? input.charAt(peg$maxFailPos) : null,
        peg$maxFailPos < input.length
          ? peg$computeLocation(peg$maxFailPos, peg$maxFailPos + 1)
          : peg$computeLocation(peg$maxFailPos, peg$maxFailPos),
      );
    }
  }

  module.exports = {
    SyntaxError: peg$SyntaxError,
    parse: peg$parse,
  };
  return module.exports as peg.Parser;
}
