/* eslint-disable no-constant-condition */
import * as peg from 'pegjs';
export default function (_: any): peg.Parser {const module = { exports: null };
/*
 * Generated by PEG.js 0.10.0.
 *
 * http://pegjs.org/
 */

"use strict";

function peg$subclass(child, parent) {
  function ctor() { this.constructor = child; }
  ctor.prototype = parent.prototype;
  child.prototype = new ctor();
}

function peg$SyntaxError(message, expected, found, location) {
  this.message  = message;
  this.expected = expected;
  this.found    = found;
  this.location = location;
  this.name     = "SyntaxError";

  if (typeof Error.captureStackTrace === "function") {
    Error.captureStackTrace(this, peg$SyntaxError);
  }
}

peg$subclass(peg$SyntaxError, Error);

peg$SyntaxError.buildMessage = function(expected, found) {
  const DESCRIBE_EXPECTATION_FNS = {
        literal: function(expectation) {
          return "\"" + literalEscape(expectation.text) + "\"";
        },

        "class": function(expectation) {
          let escapedParts = "";
              let i;

          for (i = 0; i < expectation.parts.length; i++) {
            escapedParts += expectation.parts[i] instanceof Array
              ? classEscape(expectation.parts[i][0]) + "-" + classEscape(expectation.parts[i][1])
              : classEscape(expectation.parts[i]);
          }

          return "[" + (expectation.inverted ? "^" : "") + escapedParts + "]";
        },

        any: function(expectation) {
          return "any character";
        },

        end: function(expectation) {
          return "end of input";
        },

        other: function(expectation) {
          return expectation.description;
        }
      };

  function hex(ch) {
    return ch.charCodeAt(0).toString(16).toUpperCase();
  }

  function literalEscape(s) {
    return s
      .replace(/\\/g, '\\\\')
      .replace(/"/g,  '\\"')
      .replace(/\0/g, '\\0')
      .replace(/\t/g, '\\t')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
  }

  function classEscape(s) {
    return s
      .replace(/\\/g, '\\\\')
      .replace(/\]/g, '\\]')
      .replace(/\^/g, '\\^')
      .replace(/-/g,  '\\-')
      .replace(/\0/g, '\\0')
      .replace(/\t/g, '\\t')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
  }

  function describeExpectation(expectation) {
    return DESCRIBE_EXPECTATION_FNS[expectation.type](expectation);
  }

  function describeExpected(expected) {
    const descriptions = new Array(expected.length);
        let i; let j;

    for (i = 0; i < expected.length; i++) {
      descriptions[i] = describeExpectation(expected[i]);
    }

    descriptions.sort();

    if (descriptions.length > 0) {
      for (i = 1, j = 1; i < descriptions.length; i++) {
        if (descriptions[i - 1] !== descriptions[i]) {
          descriptions[j] = descriptions[i];
          j++;
        }
      }
      descriptions.length = j;
    }

    switch (descriptions.length) {
      case 1:
        return descriptions[0];

      case 2:
        return descriptions[0] + " or " + descriptions[1];

      default:
        return descriptions.slice(0, -1).join(", ")
          + ", or "
          + descriptions[descriptions.length - 1];
    }
  }

  function describeFound(found) {
    return found ? "\"" + literalEscape(found) + "\"" : "end of input";
  }

  return "Expected " + describeExpected(expected) + " but " + describeFound(found) + " found.";
};

function peg$parse(input, options) {
  options = options !== void 0 ? options : {};

  const peg$FAILED = {};

      const peg$startRuleFunctions = { Program: peg$parseProgram };
      let peg$startRuleFunction  = peg$parseProgram;

      const peg$c0 = function(c) { return c };
      const peg$c1 = peg$otherExpectation("statement");
      const peg$c2 = peg$otherExpectation("comment");
      const peg$c3 = "//";
      const peg$c4 = peg$literalExpectation("//", false);
      const peg$c5 = /^[^\n]/;
      const peg$c6 = peg$classExpectation(["\n"], true, false);
      const peg$c7 = function() { return [] };
      const peg$c8 = "delay";
      const peg$c9 = peg$literalExpectation("delay", false);
      const peg$c10 = function(delay) { return [0x02, ..._.numberToInt32(delay)]; };
      const peg$c11 = peg$otherExpectation("halt");
      const peg$c12 = "halt";
      const peg$c13 = peg$literalExpectation("halt", false);
      const peg$c14 = function() { return [0xfe]; };
      const peg$c15 = "restart";
      const peg$c16 = peg$literalExpectation("restart", false);
      const peg$c17 = function() { return [0xfc]; };
      const peg$c18 = "noop";
      const peg$c19 = peg$literalExpectation("noop", false);
      const peg$c20 = function() { return [0x01]; };
      const peg$c21 = "sleep";
      const peg$c22 = peg$literalExpectation("sleep", false);
      const peg$c23 = function(delay) { return [0x3f, ..._.numberToInt32(delay)]; };
      const peg$c24 = "jump to";
      const peg$c25 = peg$literalExpectation("jump to", false);
      const peg$c26 = function(address) { return [0x04, ..._.numberToInt32(address)]; };
      const peg$c27 = function(t) { return [0x04, _.createPlaceholder(t), 0x00, 0x00, 0x00] };
      const peg$c28 = "yield";
      const peg$c29 = peg$literalExpectation("yield", false);
      const peg$c30 = function(delay) { return [0xfa, ..._.numberToInt32(delay)]; };
      const peg$c31 = "sysinfo";
      const peg$c32 = peg$literalExpectation("sysinfo", false);
      const peg$c33 = function() { return [0xfd]; };
      const peg$c34 = "debug";
      const peg$c35 = peg$literalExpectation("debug", false);
      const peg$c36 = function(byte) { return [0xfb, byte]; };
      const peg$c37 = "dump";
      const peg$c38 = peg$literalExpectation("dump", false);
      const peg$c39 = function() { return [0xf9]; };
      const peg$c40 = "print";
      const peg$c41 = peg$literalExpectation("print", false);
      const peg$c42 = function(string) { return [0x03, ...string]; };
      const peg$c43 = "jumpif";
      const peg$c44 = peg$literalExpectation("jumpif", false);
      const peg$c45 = function() { return [0x0f]; };
      const peg$c46 = peg$otherExpectation("label");
      const peg$c47 = /^[a-zA-Z]/;
      const peg$c48 = peg$classExpectation([["a", "z"], ["A", "Z"]], false, false);
      const peg$c49 = /^[a-zA-Z0-9_]/;
      const peg$c50 = peg$classExpectation([["a", "z"], ["A", "Z"], ["0", "9"], "_"], false, false);
      const peg$c51 = function() { return text() };
      const peg$c52 = peg$otherExpectation("new label");
      const peg$c53 = "@";
      const peg$c54 = peg$literalExpectation("@", false);
      const peg$c55 = function(label) { return _.createReference(label); };
      const peg$c56 = "memget";
      const peg$c57 = peg$literalExpectation("memget", false);
      const peg$c58 = function() { return [0x05]; };
      const peg$c59 = "memset";
      const peg$c60 = peg$literalExpectation("memset", false);
      const peg$c61 = function() { return [0x06]; };
      const peg$c62 = "push_b";
      const peg$c63 = peg$literalExpectation("push_b", false);
      const peg$c64 = function() { return [0x07]; };
      const peg$c65 = "push_i";
      const peg$c66 = peg$literalExpectation("push_i", false);
      const peg$c67 = function() { return [0x08]; };
      const peg$c68 = "copy";
      const peg$c69 = peg$literalExpectation("copy", false);
      const peg$c70 = function() { return [0x1b]; };
      const peg$c71 = "gte";
      const peg$c72 = peg$literalExpectation("gte", false);
      const peg$c73 = function() { return [0x0a]; };
      const peg$c74 = "gt";
      const peg$c75 = peg$literalExpectation("gt", false);
      const peg$c76 = function() { return [0x09]; };
      const peg$c77 = "lte";
      const peg$c78 = peg$literalExpectation("lte", false);
      const peg$c79 = function() { return [0x0c]; };
      const peg$c80 = "lt";
      const peg$c81 = peg$literalExpectation("lt", false);
      const peg$c82 = function() { return [0x0b]; };
      const peg$c83 = "equal";
      const peg$c84 = peg$literalExpectation("equal", false);
      const peg$c85 = function() { return [0x0d]; };
      const peg$c86 = "notequal";
      const peg$c87 = peg$literalExpectation("notequal", false);
      const peg$c88 = function() { return [0x0e]; };
      const peg$c89 = "xor";
      const peg$c90 = peg$literalExpectation("xor", false);
      const peg$c91 = function() { return [0x10]; };
      const peg$c92 = "and";
      const peg$c93 = peg$literalExpectation("and", false);
      const peg$c94 = function() { return [0x11]; };
      const peg$c95 = "or";
      const peg$c96 = peg$literalExpectation("or", false);
      const peg$c97 = function() { return [0x12]; };
      const peg$c98 = "not";
      const peg$c99 = peg$literalExpectation("not", false);
      const peg$c100 = function(target, operand) { return [0x13, target, operand]; };
      const peg$c101 = "inc";
      const peg$c102 = peg$literalExpectation("inc", false);
      const peg$c103 = function() { return [0x14]; };
      const peg$c104 = "dec";
      const peg$c105 = peg$literalExpectation("dec", false);
      const peg$c106 = function() { return [0x15]; };
      const peg$c107 = "add";
      const peg$c108 = peg$literalExpectation("add", false);
      const peg$c109 = function() { return [0x16]; };
      const peg$c110 = "sub";
      const peg$c111 = peg$literalExpectation("sub", false);
      const peg$c112 = function() { return [0x17]; };
      const peg$c113 = "mul";
      const peg$c114 = peg$literalExpectation("mul", false);
      const peg$c115 = function() { return [0x18]; };
      const peg$c116 = "div";
      const peg$c117 = peg$literalExpectation("div", false);
      const peg$c118 = function() { return [0x19]; };
      const peg$c119 = "mod";
      const peg$c120 = peg$literalExpectation("mod", false);
      const peg$c121 = function() { return [0x1a]; };
      const peg$c122 = "io write";
      const peg$c123 = peg$literalExpectation("io write", false);
      const peg$c124 = function() { return [0x31]; };
      const peg$c125 = "io read";
      const peg$c126 = peg$literalExpectation("io read", false);
      const peg$c127 = function() { return [0x32]; };
      const peg$c128 = "io mode";
      const peg$c129 = peg$literalExpectation("io mode", false);
      const peg$c130 = function() { return [0x35]; };
      const peg$c131 = "io type";
      const peg$c132 = peg$literalExpectation("io type", false);
      const peg$c133 = function() { return [0x36]; };
      const peg$c134 = "io allout";
      const peg$c135 = peg$literalExpectation("io allout", false);
      const peg$c136 = function() { return [0x37]; };
      const peg$c137 = "net connect";
      const peg$c138 = peg$literalExpectation("net connect", false);
      const peg$c139 = function() { return [0x3a]; };
      const peg$c140 = "net disconnect";
      const peg$c141 = peg$literalExpectation("net disconnect", false);
      const peg$c142 = function() { return [0x3b]; };
      const peg$c143 = "net status";
      const peg$c144 = peg$literalExpectation("net status", false);
      const peg$c145 = function() { return [0x3c]; };
      const peg$c146 = "wifilist";
      const peg$c147 = peg$literalExpectation("wifilist", false);
      const peg$c148 = function() { return [0x3e]; };
      const peg$c149 = "i2setup";
      const peg$c150 = peg$literalExpectation("i2setup", false);
      const peg$c151 = function() { return [0x40]; };
      const peg$c152 = "i2start";
      const peg$c153 = peg$literalExpectation("i2start", false);
      const peg$c154 = function() { return [0x41]; };
      const peg$c155 = "i2stop";
      const peg$c156 = peg$literalExpectation("i2stop", false);
      const peg$c157 = function() { return [0x42]; };
      const peg$c158 = "i2write";
      const peg$c159 = peg$literalExpectation("i2write", false);
      const peg$c160 = function() { return [0x43]; };
      const peg$c161 = "i2read";
      const peg$c162 = peg$literalExpectation("i2read", false);
      const peg$c163 = function() { return [0x44]; };
      const peg$c164 = "i2setack";
      const peg$c165 = peg$literalExpectation("i2setack", false);
      const peg$c166 = function() { return [0x45]; };
      const peg$c167 = "i2getack";
      const peg$c168 = peg$literalExpectation("i2getack", false);
      const peg$c169 = function() { return [0x46]; };
      const peg$c170 = "i2find";
      const peg$c171 = peg$literalExpectation("i2find", false);
      const peg$c172 = function() { return [0x48]; };
      const peg$c173 = "i2writeack";
      const peg$c174 = peg$literalExpectation("i2writeack", false);
      const peg$c175 = function() { return [0x49]; };
      const peg$c176 = "i2writeack_b";
      const peg$c177 = peg$literalExpectation("i2writeack_b", false);
      const peg$c178 = function() { return [0x4a]; };
      const peg$c179 = peg$otherExpectation("hexadecimal");
      const peg$c180 = /^[0-9A-Fa-f]/;
      const peg$c181 = peg$classExpectation([["0", "9"], ["A", "F"], ["a", "f"]], false, false);
      const peg$c182 = peg$otherExpectation("integer");
      const peg$c183 = /^[1-9]/;
      const peg$c184 = peg$classExpectation([["1", "9"]], false, false);
      const peg$c185 = /^[0-9]/;
      const peg$c186 = peg$classExpectation([["0", "9"]], false, false);
      const peg$c187 = function() { return Number(text()) };
      const peg$c188 = peg$otherExpectation("string");
      const peg$c189 = "'";
      const peg$c190 = peg$literalExpectation("'", false);
      const peg$c191 = peg$anyExpectation();
      const peg$c192 = function(string) { return _.toBinaryString(string.map(s => s[1])) };
      const peg$c193 = peg$otherExpectation("space");
      const peg$c194 = /^[ \t]/;
      const peg$c195 = peg$classExpectation([" ", "\t"], false, false);
      const peg$c196 = peg$otherExpectation("new line");
      const peg$c197 = /^[\n]/;
      const peg$c198 = peg$classExpectation(["\n"], false, false);
      const peg$c199 = peg$otherExpectation("HexByte");
      const peg$c200 = peg$otherExpectation("Byte");
      const peg$c201 = function() { return _.bytesFromHex(text()) };
      const peg$c202 = peg$otherExpectation("separator");
      const peg$c203 = ",";
      const peg$c204 = peg$literalExpectation(",", false);
      const peg$c205 = peg$otherExpectation("0..9");
      const peg$c206 = peg$otherExpectation("pin mode");
      const peg$c207 = /^[0-3]/;
      const peg$c208 = peg$classExpectation([["0", "3"]], false, false);
      const peg$c209 = function(mode) { return Number(mode) };
      const peg$c210 = peg$otherExpectation("variable");
      const peg$c211 = "#";
      const peg$c212 = peg$literalExpectation("#", false);
      const peg$c213 = function(d) { return Number(d) };
      const peg$c214 = peg$otherExpectation("address");
      const peg$c215 = "0x";
      const peg$c216 = peg$literalExpectation("0x", false);
      const peg$c217 = function(a, b, c, d) { return _.int32ToNumber([d, c, b, a]) };
      const peg$c218 = peg$otherExpectation("pin");
      const peg$c219 = "pin ";
      const peg$c220 = peg$literalExpectation("pin ", false);
      const peg$c221 = function(pin) { return Number(pin) };
      const peg$c222 = peg$otherExpectation("operand");
      const peg$c223 = "true";
      const peg$c224 = peg$literalExpectation("true", false);
      const peg$c225 = function() { return 1 };
      const peg$c226 = "false";
      const peg$c227 = peg$literalExpectation("false", false);
      const peg$c228 = function() { return 0 };

      let peg$currPos          = 0;
      let peg$savedPos         = 0;
      const peg$posDetailsCache  = [{ line: 1, column: 1 }];
      let peg$maxFailPos       = 0;
      let peg$maxFailExpected  = [];
      let peg$silentFails      = 0;

      let peg$result;

  if ("startRule" in options) {
    if (!(options.startRule in peg$startRuleFunctions)) {
      throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");
    }

    peg$startRuleFunction = peg$startRuleFunctions[options.startRule];
  }

  function text() {
    return input.substring(peg$savedPos, peg$currPos);
  }

  function location() {
    return peg$computeLocation(peg$savedPos, peg$currPos);
  }

  function expected(description, location) {
    location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

    throw peg$buildStructuredError(
      [peg$otherExpectation(description)],
      input.substring(peg$savedPos, peg$currPos),
      location
    );
  }

  function error(message, location) {
    location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

    throw peg$buildSimpleError(message, location);
  }

  function peg$literalExpectation(text, ignoreCase) {
    return { type: "literal", text: text, ignoreCase: ignoreCase };
  }

  function peg$classExpectation(parts, inverted, ignoreCase) {
    return { type: "class", parts: parts, inverted: inverted, ignoreCase: ignoreCase };
  }

  function peg$anyExpectation() {
    return { type: "any" };
  }

  function peg$endExpectation() {
    return { type: "end" };
  }

  function peg$otherExpectation(description) {
    return { type: "other", description: description };
  }

  function peg$computePosDetails(pos) {
    let details = peg$posDetailsCache[pos]; let p;

    if (details) {
      return details;
    } else {
      p = pos - 1;
      while (!peg$posDetailsCache[p]) {
        p--;
      }

      details = peg$posDetailsCache[p];
      details = {
        line:   details.line,
        column: details.column
      };

      while (p < pos) {
        if (input.charCodeAt(p) === 10) {
          details.line++;
          details.column = 1;
        } else {
          details.column++;
        }

        p++;
      }

      peg$posDetailsCache[pos] = details;
      return details;
    }
  }

  function peg$computeLocation(startPos, endPos) {
    const startPosDetails = peg$computePosDetails(startPos);
        const endPosDetails   = peg$computePosDetails(endPos);

    return {
      start: {
        offset: startPos,
        line:   startPosDetails.line,
        column: startPosDetails.column
      },
      end: {
        offset: endPos,
        line:   endPosDetails.line,
        column: endPosDetails.column
      }
    };
  }

  function peg$fail(expected) {
    if (peg$currPos < peg$maxFailPos) { return; }

    if (peg$currPos > peg$maxFailPos) {
      peg$maxFailPos = peg$currPos;
      peg$maxFailExpected = [];
    }

    peg$maxFailExpected.push(expected);
  }

  function peg$buildSimpleError(message, location) {
    return new peg$SyntaxError(message, null, null, location);
  }

  function peg$buildStructuredError(expected, found, location) {
    return new peg$SyntaxError(
      peg$SyntaxError.buildMessage(expected, found),
      expected,
      found,
      location
    );
  }

  function peg$parseProgram() {
    let s0; let s1; let s2;

    s0 = peg$currPos;
    s1 = [];
    s2 = peg$parseLine();
    while (s2 !== peg$FAILED) {
      s1.push(s2);
      s2 = peg$parseLine();
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c0(s1);
    }
    s0 = s1;

    return s0;
  }

  function peg$parseLine() {
    let s0; let s1; let s2; let s3;

    peg$silentFails++;
    s0 = peg$currPos;
    s1 = peg$parseSpaces();
    if (s1 !== peg$FAILED) {
      s2 = peg$parseStatement();
      if (s2 !== peg$FAILED) {
        s3 = peg$parseNewLine();
        if (s3 === peg$FAILED) {
          s3 = null;
        }
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c0(s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c1); }
    }

    return s0;
  }

  function peg$parseComment() {
    let s0; let s1; let s2; let s3; let s4;

    peg$silentFails++;
    s0 = peg$currPos;
    s1 = peg$currPos;
    if (input.substr(peg$currPos, 2) === peg$c3) {
      s2 = peg$c3;
      peg$currPos += 2;
    } else {
      s2 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c4); }
    }
    if (s2 !== peg$FAILED) {
      s3 = [];
      if (peg$c5.test(input.charAt(peg$currPos))) {
        s4 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s4 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c6); }
      }
      if (s4 !== peg$FAILED) {
        while (s4 !== peg$FAILED) {
          s3.push(s4);
          if (peg$c5.test(input.charAt(peg$currPos))) {
            s4 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s4 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$c6); }
          }
        }
      } else {
        s3 = peg$FAILED;
      }
      if (s3 !== peg$FAILED) {
        s2 = [s2, s3];
        s1 = s2;
      } else {
        peg$currPos = s1;
        s1 = peg$FAILED;
      }
    } else {
      peg$currPos = s1;
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c7();
    }
    s0 = s1;
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c2); }
    }

    return s0;
  }

  function peg$parseStatement() {
    let s0; let s1;

    peg$silentFails++;
    s0 = peg$parseDefineTag();
    if (s0 === peg$FAILED) {
      s0 = peg$parseSystemInstruction();
      if (s0 === peg$FAILED) {
        s0 = peg$parseMemoryInstruction();
        if (s0 === peg$FAILED) {
          s0 = peg$parseOperator();
          if (s0 === peg$FAILED) {
            s0 = peg$parseIoInstruction();
            if (s0 === peg$FAILED) {
              s0 = peg$parseWifiInstruction();
              if (s0 === peg$FAILED) {
                s0 = peg$parseI2cInstruction();
                if (s0 === peg$FAILED) {
                  s0 = peg$parseComment();
                }
              }
            }
          }
        }
      }
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c1); }
    }

    return s0;
  }

  function peg$parseSystemInstruction() {
    let s0;

    s0 = peg$parsehalt();
    if (s0 === peg$FAILED) {
      s0 = peg$parserestart();
      if (s0 === peg$FAILED) {
        s0 = peg$parsesysinfo();
        if (s0 === peg$FAILED) {
          s0 = peg$parsedebug();
          if (s0 === peg$FAILED) {
            s0 = peg$parsedump();
            if (s0 === peg$FAILED) {
              s0 = peg$parsenoop();
              if (s0 === peg$FAILED) {
                s0 = peg$parseyield();
                if (s0 === peg$FAILED) {
                  s0 = peg$parseprint();
                  if (s0 === peg$FAILED) {
                    s0 = peg$parsejump_to();
                    if (s0 === peg$FAILED) {
                      s0 = peg$parsejumpif();
                      if (s0 === peg$FAILED) {
                        s0 = peg$parsedelay();
                        if (s0 === peg$FAILED) {
                          s0 = peg$parsesleep();
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

    return s0;
  }

  function peg$parsedelay() {
    let s0; let s1; let s2; let s3;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 5) === peg$c8) {
      s1 = peg$c8;
      peg$currPos += 5;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c9); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s3 = peg$parseInteger();
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c10(s3);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    return s0;
  }

  function peg$parsehalt() {
    let s0; let s1;

    peg$silentFails++;
    s0 = peg$currPos;
    if (input.substr(peg$currPos, 4) === peg$c12) {
      s1 = peg$c12;
      peg$currPos += 4;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c13); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c14();
    }
    s0 = s1;
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c11); }
    }

    return s0;
  }

  function peg$parserestart() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 7) === peg$c15) {
      s1 = peg$c15;
      peg$currPos += 7;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c16); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c17();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsenoop() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 4) === peg$c18) {
      s1 = peg$c18;
      peg$currPos += 4;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c19); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c20();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsesleep() {
    let s0; let s1; let s2; let s3;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 5) === peg$c21) {
      s1 = peg$c21;
      peg$currPos += 5;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c22); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s3 = peg$parseInteger();
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c23(s3);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    return s0;
  }

  function peg$parsejump_to() {
    let s0; let s1; let s2; let s3;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 7) === peg$c24) {
      s1 = peg$c24;
      peg$currPos += 7;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c25); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s3 = peg$parseAddress();
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c26(s3);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    if (s0 === peg$FAILED) {
      s0 = peg$currPos;
      if (input.substr(peg$currPos, 7) === peg$c24) {
        s1 = peg$c24;
        peg$currPos += 7;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c25); }
      }
      if (s1 !== peg$FAILED) {
        s2 = peg$parseSpaces();
        if (s2 !== peg$FAILED) {
          s3 = peg$parseLabel();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c27(s3);
            s0 = s1;
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    }

    return s0;
  }

  function peg$parseyield() {
    let s0; let s1; let s2; let s3;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 5) === peg$c28) {
      s1 = peg$c28;
      peg$currPos += 5;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c29); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s3 = peg$parseInteger();
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c30(s3);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    return s0;
  }

  function peg$parsesysinfo() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 7) === peg$c31) {
      s1 = peg$c31;
      peg$currPos += 7;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c32); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c33();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsedebug() {
    let s0; let s1; let s2; let s3;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 5) === peg$c34) {
      s1 = peg$c34;
      peg$currPos += 5;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c35); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s3 = peg$parseBoolean();
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c36(s3);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    return s0;
  }

  function peg$parsedump() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 4) === peg$c37) {
      s1 = peg$c37;
      peg$currPos += 4;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c38); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c39();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseprint() {
    let s0; let s1; let s2; let s3;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 5) === peg$c40) {
      s1 = peg$c40;
      peg$currPos += 5;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c41); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s3 = peg$parseString();
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c42(s3);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    return s0;
  }

  function peg$parsejumpif() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 6) === peg$c43) {
      s1 = peg$c43;
      peg$currPos += 6;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c44); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c45();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseLabel() {
    let s0; let s1; let s2; let s3;

    peg$silentFails++;
    s0 = peg$currPos;
    s1 = [];
    if (peg$c47.test(input.charAt(peg$currPos))) {
      s2 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s2 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c48); }
    }
    if (s2 !== peg$FAILED) {
      while (s2 !== peg$FAILED) {
        s1.push(s2);
        if (peg$c47.test(input.charAt(peg$currPos))) {
          s2 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c48); }
        }
      }
    } else {
      s1 = peg$FAILED;
    }
    if (s1 !== peg$FAILED) {
      s2 = [];
      if (peg$c49.test(input.charAt(peg$currPos))) {
        s3 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s3 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c50); }
      }
      while (s3 !== peg$FAILED) {
        s2.push(s3);
        if (peg$c49.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c50); }
        }
      }
      if (s2 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c51();
        s0 = s1;
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c46); }
    }

    return s0;
  }

  function peg$parseDefineTag() {
    let s0; let s1; let s2;

    peg$silentFails++;
    s0 = peg$currPos;
    if (input.charCodeAt(peg$currPos) === 64) {
      s1 = peg$c53;
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c54); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseLabel();
      if (s2 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c55(s2);
        s0 = s1;
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c52); }
    }

    return s0;
  }

  function peg$parseMemoryInstruction() {
    let s0;

    s0 = peg$parsememget();
    if (s0 === peg$FAILED) {
      s0 = peg$parsememset();
      if (s0 === peg$FAILED) {
        s0 = peg$parsepush_b();
        if (s0 === peg$FAILED) {
          s0 = peg$parsepush_i();
          if (s0 === peg$FAILED) {
            s0 = peg$parsecopy();
          }
        }
      }
    }

    return s0;
  }

  function peg$parsememget() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 6) === peg$c56) {
      s1 = peg$c56;
      peg$currPos += 6;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c57); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c58();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsememset() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 6) === peg$c59) {
      s1 = peg$c59;
      peg$currPos += 6;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c60); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c61();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsepush_b() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 6) === peg$c62) {
      s1 = peg$c62;
      peg$currPos += 6;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c63); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c64();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsepush_i() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 6) === peg$c65) {
      s1 = peg$c65;
      peg$currPos += 6;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c66); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c67();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsecopy() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 4) === peg$c68) {
      s1 = peg$c68;
      peg$currPos += 4;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c69); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c70();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseOperator() {
    let s0;

    s0 = peg$parsexor();
    if (s0 === peg$FAILED) {
      s0 = peg$parseand();
      if (s0 === peg$FAILED) {
        s0 = peg$parseor();
        if (s0 === peg$FAILED) {
          s0 = peg$parsenot();
          if (s0 === peg$FAILED) {
            s0 = peg$parseinc();
            if (s0 === peg$FAILED) {
              s0 = peg$parsedec();
              if (s0 === peg$FAILED) {
                s0 = peg$parseadd();
                if (s0 === peg$FAILED) {
                  s0 = peg$parsesub();
                  if (s0 === peg$FAILED) {
                    s0 = peg$parsemul();
                    if (s0 === peg$FAILED) {
                      s0 = peg$parsediv();
                      if (s0 === peg$FAILED) {
                        s0 = peg$parsemod();
                        if (s0 === peg$FAILED) {
                          s0 = peg$parsegt();
                          if (s0 === peg$FAILED) {
                            s0 = peg$parsegte();
                            if (s0 === peg$FAILED) {
                              s0 = peg$parselt();
                              if (s0 === peg$FAILED) {
                                s0 = peg$parselte();
                                if (s0 === peg$FAILED) {
                                  s0 = peg$parseequal();
                                  if (s0 === peg$FAILED) {
                                    s0 = peg$parsenotequal();
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

    return s0;
  }

  function peg$parsegte() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c71) {
      s1 = peg$c71;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c72); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c73();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsegt() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 2) === peg$c74) {
      s1 = peg$c74;
      peg$currPos += 2;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c75); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c76();
    }
    s0 = s1;

    return s0;
  }

  function peg$parselte() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c77) {
      s1 = peg$c77;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c78); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c79();
    }
    s0 = s1;

    return s0;
  }

  function peg$parselt() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 2) === peg$c80) {
      s1 = peg$c80;
      peg$currPos += 2;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c81); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c82();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseequal() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 5) === peg$c83) {
      s1 = peg$c83;
      peg$currPos += 5;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c84); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c85();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsenotequal() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 8) === peg$c86) {
      s1 = peg$c86;
      peg$currPos += 8;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c87); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c88();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsexor() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c89) {
      s1 = peg$c89;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c90); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c91();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseand() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c92) {
      s1 = peg$c92;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c93); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c94();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseor() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 2) === peg$c95) {
      s1 = peg$c95;
      peg$currPos += 2;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c96); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c97();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsenot() {
    let s0; let s1; let s2; let s3; let s4; let s5;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c98) {
      s1 = peg$c98;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c99); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s3 = peg$parseVariable();
        if (s3 !== peg$FAILED) {
          s4 = peg$parseSeparator();
          if (s4 !== peg$FAILED) {
            s5 = peg$parseOperand();
            if (s5 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c100(s3, s5);
              s0 = s1;
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    return s0;
  }

  function peg$parseinc() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c101) {
      s1 = peg$c101;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c102); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c103();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsedec() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c104) {
      s1 = peg$c104;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c105); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c106();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseadd() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c107) {
      s1 = peg$c107;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c108); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c109();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsesub() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c110) {
      s1 = peg$c110;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c111); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c112();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsemul() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c113) {
      s1 = peg$c113;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c114); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c115();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsediv() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c116) {
      s1 = peg$c116;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c117); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c118();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsemod() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 3) === peg$c119) {
      s1 = peg$c119;
      peg$currPos += 3;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c120); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c121();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseIoInstruction() {
    let s0;

    s0 = peg$parseiowrite();
    if (s0 === peg$FAILED) {
      s0 = peg$parseioread();
      if (s0 === peg$FAILED) {
        s0 = peg$parseiomode();
        if (s0 === peg$FAILED) {
          s0 = peg$parseiotype();
          if (s0 === peg$FAILED) {
            s0 = peg$parseioallout();
          }
        }
      }
    }

    return s0;
  }

  function peg$parseiowrite() {
    let s0; let s1; let s2; let s3; let s4; let s5;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 8) === peg$c122) {
      s1 = peg$c122;
      peg$currPos += 8;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c123); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s3 = peg$parsePin();
        if (s3 !== peg$FAILED) {
          s4 = peg$parseSeparator();
          if (s4 !== peg$FAILED) {
            s5 = peg$parseOperand();
            if (s5 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c124();
              s0 = s1;
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    return s0;
  }

  function peg$parseioread() {
    let s0; let s1; let s2; let s3; let s4; let s5;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 7) === peg$c125) {
      s1 = peg$c125;
      peg$currPos += 7;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c126); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s3 = peg$parsePin();
        if (s3 !== peg$FAILED) {
          s4 = peg$parseSeparator();
          if (s4 !== peg$FAILED) {
            s5 = peg$parseOperand();
            if (s5 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c127();
              s0 = s1;
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    return s0;
  }

  function peg$parseiomode() {
    let s0; let s1; let s2; let s3; let s4; let s5;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 7) === peg$c128) {
      s1 = peg$c128;
      peg$currPos += 7;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c129); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s3 = peg$parsePin();
        if (s3 !== peg$FAILED) {
          s4 = peg$parseSeparator();
          if (s4 !== peg$FAILED) {
            s5 = peg$parsePinMode();
            if (s5 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c130();
              s0 = s1;
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    return s0;
  }

  function peg$parseiotype() {
    let s0; let s1; let s2; let s3; let s4; let s5;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 7) === peg$c131) {
      s1 = peg$c131;
      peg$currPos += 7;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c132); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s3 = peg$parsePin();
        if (s3 !== peg$FAILED) {
          s4 = peg$parseSeparator();
          if (s4 !== peg$FAILED) {
            s5 = peg$parseDigit();
            if (s5 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c133();
              s0 = s1;
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }

    return s0;
  }

  function peg$parseioallout() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 9) === peg$c134) {
      s1 = peg$c134;
      peg$currPos += 9;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c135); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c136();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseWifiInstruction() {
    let s0;

    s0 = peg$parsewificonnect();
    if (s0 === peg$FAILED) {
      s0 = peg$parsewifidisconnect();
      if (s0 === peg$FAILED) {
        s0 = peg$parsewifistatus();
        if (s0 === peg$FAILED) {
          s0 = peg$parsewifilist();
        }
      }
    }

    return s0;
  }

  function peg$parsewificonnect() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 11) === peg$c137) {
      s1 = peg$c137;
      peg$currPos += 11;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c138); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c139();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsewifidisconnect() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 14) === peg$c140) {
      s1 = peg$c140;
      peg$currPos += 14;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c141); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c142();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsewifistatus() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 10) === peg$c143) {
      s1 = peg$c143;
      peg$currPos += 10;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c144); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c145();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsewifilist() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 8) === peg$c146) {
      s1 = peg$c146;
      peg$currPos += 8;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c147); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c148();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseI2cInstruction() {
    let s0;

    s0 = peg$parsei2setup();
    if (s0 === peg$FAILED) {
      s0 = peg$parsei2start();
      if (s0 === peg$FAILED) {
        s0 = peg$parsei2stop();
        if (s0 === peg$FAILED) {
          s0 = peg$parsei2write();
          if (s0 === peg$FAILED) {
            s0 = peg$parsei2read();
            if (s0 === peg$FAILED) {
              s0 = peg$parsei2setack();
              if (s0 === peg$FAILED) {
                s0 = peg$parsei2getack();
                if (s0 === peg$FAILED) {
                  s0 = peg$parsei2find();
                  if (s0 === peg$FAILED) {
                    s0 = peg$parsei2writeack();
                    if (s0 === peg$FAILED) {
                      s0 = peg$parsei2writeack_b();
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

    return s0;
  }

  function peg$parsei2setup() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 7) === peg$c149) {
      s1 = peg$c149;
      peg$currPos += 7;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c150); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c151();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsei2start() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 7) === peg$c152) {
      s1 = peg$c152;
      peg$currPos += 7;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c153); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c154();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsei2stop() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 6) === peg$c155) {
      s1 = peg$c155;
      peg$currPos += 6;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c156); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c157();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsei2write() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 7) === peg$c158) {
      s1 = peg$c158;
      peg$currPos += 7;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c159); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c160();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsei2read() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 6) === peg$c161) {
      s1 = peg$c161;
      peg$currPos += 6;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c162); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c163();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsei2setack() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 8) === peg$c164) {
      s1 = peg$c164;
      peg$currPos += 8;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c165); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c166();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsei2getack() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 8) === peg$c167) {
      s1 = peg$c167;
      peg$currPos += 8;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c168); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c169();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsei2find() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 6) === peg$c170) {
      s1 = peg$c170;
      peg$currPos += 6;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c171); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c172();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsei2writeack() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 10) === peg$c173) {
      s1 = peg$c173;
      peg$currPos += 10;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c174); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c175();
    }
    s0 = s1;

    return s0;
  }

  function peg$parsei2writeack_b() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 12) === peg$c176) {
      s1 = peg$c176;
      peg$currPos += 12;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c177); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c178();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseHexDigit() {
    let s0; let s1;

    peg$silentFails++;
    if (peg$c180.test(input.charAt(peg$currPos))) {
      s0 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s0 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c181); }
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c179); }
    }

    return s0;
  }

  function peg$parseInteger() {
    let s0; let s1; let s2; let s3;

    peg$silentFails++;
    s0 = peg$currPos;
    if (peg$c183.test(input.charAt(peg$currPos))) {
      s1 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c184); }
    }
    if (s1 !== peg$FAILED) {
      s2 = [];
      if (peg$c185.test(input.charAt(peg$currPos))) {
        s3 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s3 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c186); }
      }
      while (s3 !== peg$FAILED) {
        s2.push(s3);
        if (peg$c185.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c186); }
        }
      }
      if (s2 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c187();
        s0 = s1;
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c182); }
    }

    return s0;
  }

  function peg$parseString() {
    let s0; let s1; let s2; let s3; let s4; let s5;

    peg$silentFails++;
    s0 = peg$currPos;
    if (input.charCodeAt(peg$currPos) === 39) {
      s1 = peg$c189;
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c190); }
    }
    if (s1 !== peg$FAILED) {
      s2 = [];
      s3 = peg$currPos;
      s4 = peg$currPos;
      peg$silentFails++;
      if (input.charCodeAt(peg$currPos) === 39) {
        s5 = peg$c189;
        peg$currPos++;
      } else {
        s5 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c190); }
      }
      peg$silentFails--;
      if (s5 === peg$FAILED) {
        s4 = void 0;
      } else {
        peg$currPos = s4;
        s4 = peg$FAILED;
      }
      if (s4 !== peg$FAILED) {
        if (input.length > peg$currPos) {
          s5 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s5 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c191); }
        }
        if (s5 !== peg$FAILED) {
          s4 = [s4, s5];
          s3 = s4;
        } else {
          peg$currPos = s3;
          s3 = peg$FAILED;
        }
      } else {
        peg$currPos = s3;
        s3 = peg$FAILED;
      }
      while (s3 !== peg$FAILED) {
        s2.push(s3);
        s3 = peg$currPos;
        s4 = peg$currPos;
        peg$silentFails++;
        if (input.charCodeAt(peg$currPos) === 39) {
          s5 = peg$c189;
          peg$currPos++;
        } else {
          s5 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c190); }
        }
        peg$silentFails--;
        if (s5 === peg$FAILED) {
          s4 = void 0;
        } else {
          peg$currPos = s4;
          s4 = peg$FAILED;
        }
        if (s4 !== peg$FAILED) {
          if (input.length > peg$currPos) {
            s5 = input.charAt(peg$currPos);
            peg$currPos++;
          } else {
            s5 = peg$FAILED;
            if (peg$silentFails === 0) { peg$fail(peg$c191); }
          }
          if (s5 !== peg$FAILED) {
            s4 = [s4, s5];
            s3 = s4;
          } else {
            peg$currPos = s3;
            s3 = peg$FAILED;
          }
        } else {
          peg$currPos = s3;
          s3 = peg$FAILED;
        }
      }
      if (s2 !== peg$FAILED) {
        if (input.charCodeAt(peg$currPos) === 39) {
          s3 = peg$c189;
          peg$currPos++;
        } else {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c190); }
        }
        if (s3 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c192(s2);
          s0 = s1;
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c188); }
    }

    return s0;
  }

  function peg$parseSpaces() {
    let s0; let s1;

    peg$silentFails++;
    s0 = [];
    if (peg$c194.test(input.charAt(peg$currPos))) {
      s1 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c195); }
    }
    while (s1 !== peg$FAILED) {
      s0.push(s1);
      if (peg$c194.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;
      } else {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) { peg$fail(peg$c195); }
      }
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c193); }
    }

    return s0;
  }

  function peg$parseNewLine() {
    let s0; let s1;

    peg$silentFails++;
    s0 = [];
    if (peg$c197.test(input.charAt(peg$currPos))) {
      s1 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c198); }
    }
    if (s1 !== peg$FAILED) {
      while (s1 !== peg$FAILED) {
        s0.push(s1);
        if (peg$c197.test(input.charAt(peg$currPos))) {
          s1 = input.charAt(peg$currPos);
          peg$currPos++;
        } else {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) { peg$fail(peg$c198); }
        }
      }
    } else {
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c196); }
    }

    return s0;
  }

  function peg$parseHexByte() {
    let s0; let s1; let s2;

    peg$silentFails++;
    s0 = peg$currPos;
    s1 = peg$parseHexDigit();
    if (s1 !== peg$FAILED) {
      s2 = peg$parseHexDigit();
      if (s2 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c51();
        s0 = s1;
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c199); }
    }

    return s0;
  }

  function peg$parseByte() {
    let s0; let s1; let s2;

    peg$silentFails++;
    s0 = peg$currPos;
    s1 = peg$parseHexDigit();
    if (s1 !== peg$FAILED) {
      s2 = peg$parseHexDigit();
      if (s2 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c201();
        s0 = s1;
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c200); }
    }

    return s0;
  }

  function peg$parseSeparator() {
    let s0; let s1; let s2;

    peg$silentFails++;
    s0 = peg$currPos;
    if (input.charCodeAt(peg$currPos) === 44) {
      s1 = peg$c203;
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c204); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseSpaces();
      if (s2 !== peg$FAILED) {
        s1 = [s1, s2];
        s0 = s1;
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c202); }
    }

    return s0;
  }

  function peg$parseDigit() {
    let s0; let s1;

    peg$silentFails++;
    if (peg$c185.test(input.charAt(peg$currPos))) {
      s0 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s0 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c186); }
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c205); }
    }

    return s0;
  }

  function peg$parsePinMode() {
    let s0; let s1;

    peg$silentFails++;
    s0 = peg$currPos;
    if (peg$c207.test(input.charAt(peg$currPos))) {
      s1 = input.charAt(peg$currPos);
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c208); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c209(s1);
    }
    s0 = s1;
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c206); }
    }

    return s0;
  }

  function peg$parseVariable() {
    let s0; let s1; let s2;

    peg$silentFails++;
    s0 = peg$currPos;
    if (input.charCodeAt(peg$currPos) === 35) {
      s1 = peg$c211;
      peg$currPos++;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c212); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseDigit();
      if (s2 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c213(s2);
        s0 = s1;
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c210); }
    }

    return s0;
  }

  function peg$parseAddress() {
    let s0; let s1; let s2; let s3; let s4; let s5;

    peg$silentFails++;
    s0 = peg$currPos;
    if (input.substr(peg$currPos, 2) === peg$c215) {
      s1 = peg$c215;
      peg$currPos += 2;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c216); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseByte();
      if (s2 !== peg$FAILED) {
        s3 = peg$parseByte();
        if (s3 !== peg$FAILED) {
          s4 = peg$parseByte();
          if (s4 !== peg$FAILED) {
            s5 = peg$parseByte();
            if (s5 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c217(s2, s3, s4, s5);
              s0 = s1;
            } else {
              peg$currPos = s0;
              s0 = peg$FAILED;
            }
          } else {
            peg$currPos = s0;
            s0 = peg$FAILED;
          }
        } else {
          peg$currPos = s0;
          s0 = peg$FAILED;
        }
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c214); }
    }

    return s0;
  }

  function peg$parsePin() {
    let s0; let s1; let s2;

    peg$silentFails++;
    s0 = peg$currPos;
    if (input.substr(peg$currPos, 4) === peg$c219) {
      s1 = peg$c219;
      peg$currPos += 4;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c220); }
    }
    if (s1 !== peg$FAILED) {
      s2 = peg$parseDigit();
      if (s2 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c221(s2);
        s0 = s1;
      } else {
        peg$currPos = s0;
        s0 = peg$FAILED;
      }
    } else {
      peg$currPos = s0;
      s0 = peg$FAILED;
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c218); }
    }

    return s0;
  }

  function peg$parseOperand() {
    let s0; let s1;

    peg$silentFails++;
    s0 = peg$parseVariable();
    if (s0 === peg$FAILED) {
      s0 = peg$parseAddress();
      if (s0 === peg$FAILED) {
        s0 = peg$parsePin();
      }
    }
    peg$silentFails--;
    if (s0 === peg$FAILED) {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c222); }
    }

    return s0;
  }

  function peg$parseTrue() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 4) === peg$c223) {
      s1 = peg$c223;
      peg$currPos += 4;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c224); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c225();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseFalse() {
    let s0; let s1;

    s0 = peg$currPos;
    if (input.substr(peg$currPos, 5) === peg$c226) {
      s1 = peg$c226;
      peg$currPos += 5;
    } else {
      s1 = peg$FAILED;
      if (peg$silentFails === 0) { peg$fail(peg$c227); }
    }
    if (s1 !== peg$FAILED) {
      peg$savedPos = s0;
      s1 = peg$c228();
    }
    s0 = s1;

    return s0;
  }

  function peg$parseBoolean() {
    let s0;

    s0 = peg$parseTrue();
    if (s0 === peg$FAILED) {
      s0 = peg$parseFalse();
    }

    return s0;
  }

  peg$result = peg$startRuleFunction();

  if (peg$result !== peg$FAILED && peg$currPos === input.length) {
    return peg$result;
  } else {
    if (peg$result !== peg$FAILED && peg$currPos < input.length) {
      peg$fail(peg$endExpectation());
    }

    throw peg$buildStructuredError(
      peg$maxFailExpected,
      peg$maxFailPos < input.length ? input.charAt(peg$maxFailPos) : null,
      peg$maxFailPos < input.length
        ? peg$computeLocation(peg$maxFailPos, peg$maxFailPos + 1)
        : peg$computeLocation(peg$maxFailPos, peg$maxFailPos)
    );
  }
}

module.exports = {
  SyntaxError: peg$SyntaxError,
  parse:       peg$parse
};
return module.exports as peg.Parser;}
