name: Tests

on:
  - push

jobs:
  check:
    name: Build & Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: ci
        run: npm run ci

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/checkout@v3
      - name: Semantic Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          npm ci
          npm run build
          npx semantic-release
