name: Tests

on:
  - push

jobs:
  release:
    uses: cloud-cli/workflows/.github/workflows/npm-build-release.yml@main
    with:
      buildCommand: 'npm run ci'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}